### ISSUE TITLE
Colorado tax rates inaccurate

### ISSUE THREAD

**Issue by asuh** [Automattic/woocommerce-services#1934] opened 2020-02-27 02:59 UTC
The WC site I'm administering seems to be applying inaccurate tax rates. I never applied a tax plugin since I thought I read that this plugin has that built in. It's possible this is related to https://github.com/Automattic/woocommerce-services/issues/1867.

When I reviewed some of the tax rates at `/wp-admin/admin.php?page=wc-settings&tab=tax&section=standard`, multiple rates don't appear accurate. Additionally, it appears Colorado sales tax are primarily based on the Jurisdiction Codes for a County or City. WC has Zip and City but I don't understand how that translates to these Jurisdiction Codes.

I'm not sure how to troubleshoot this without either entering rates manually (which, I can't really use the Jurisdiction Code) or using another plugin. If I decide to install the Taxjar plugin, is it any different than what this plugin is already importing from Taxjar?

For reference, I think the most current rates can be found here:
https://www.colorado.gov/pacific/tax/sales-and-use-tax-rates-lookup

Thanks for the help.

-----------------------------------------------------------

EDIT: September 22, 2020

For purposes of privacy, adhering to GDPR, and to protect identities, I am giving estimated addresses that duplicate the same rates and issues as the original addresses.

I tested this on both a staging site and live site, getting the same incorrect tax rate.

**Origin address**
26851 Rd P
Dolores, Colorado 81323

**Destination address**
4634 Simms St.
Wheat Ridge, CO 80033

For this destination address, I added one product for $20.95. 

![Screen Shot 2020-09-22 at 22 51 25](https://user-images.githubusercontent.com/454064/93971961-3354c700-fd26-11ea-97b3-1fa4c4f2d654.png)

The tax rate being applied is 4.5%, which is what was imported into WooCommerce at some point, found at `wp-admin/admin.php?page=wc-settings&tab=tax&section=standard`:

![Screen Shot 2020-09-22 at 22 53 04](https://user-images.githubusercontent.com/454064/93972053-68f9b000-fd26-11ea-8499-b5d5fdff0877.png)

[According to TaxJar](https://www.taxjar.com/sales-tax-calculator/), the rate should be 8%:

![Screen Shot 2020-09-22 at 22 54 40](https://user-images.githubusercontent.com/454064/93972164-9f372f80-fd26-11ea-801e-65f2f2119113.png)

- Is it possible the imported tax rate into WooCommerce was originally imported incorrectly? 
- Are developers supposed to have an external mechanism to update these rates?
- Will WooCommerce Services plugin update tax rates when the plugin is updated?

**Comment by spraveenitpro** [comment] 2020-03-12 10:33
Even Ohio Tax rates do not see to work, the district rate is 1% as per Taxjar which makes the tax 8%:

![](https://d.pr/i/r6FmSR+)
[Direct Link](https://d.pr/i/r6FmSR+)

But on the checkout page we see 7%:

![](https://d.pr/i/MpKtrw+)
[Direct Link](https://d.pr/i/MpKtrw+)

**Comment by mdmoore** [comment] 2020-04-23 15:52
Another report of this in 2885994-zen.  In this case, Loveland sales tax isn't charging the cities rate of 3%.

**Comment by stephhjacq** [comment] 2020-09-10 20:54
Another report in 24029039-hc
Westminster, CO 80021 charged $2.25 instead of $4.17

**Comment by FreshPhil** [comment] 2020-09-13 00:37
@stephhjacq the interaction that you quoted doesn't seem to have an issue (I'll provide more details in slack).

**Comment by FreshPhil** [comment] 2020-09-13 01:00
@asuh Could you please reply back with specific scenarios, including origin/destination addresses, as well as the order subtotal and tax amount. That way we can take a look.

I've ran several tests for addresses within Colorado and the rates matched other tax calculation resources.

One important thing to keep in mind specific to Colorado is that it has a unique way of calculating sales tax. To understand how Colorado sales tax is calculated, please see this guide:

https://www.taxjar.com/states/colorado-sales-tax-online/#how-to-collect-sales-tax-in-colorado

**Comment by asuh** [comment] 2020-09-23 06:00
Hello @FreshPhil, thanks for your attention to this. I have updated the original post with more information.

Let me know if you need any additional information to troubleshoot this problem. Thanks again.

**Comment by FreshPhil** [comment] 2020-09-23 19:14
Hi @asuh - thank you for that updated information.

The reason for the rate discrepency that you are seeing on WooCommerce version the TaxJar rate tool is that these are not an equal comparison.

The TaxJar rate tool is telling you what the tax rate for `4634 Simms St. Wheat Ridge, CO 80033` is.

That is **not** the same as the tax for a product sold from:
`26851 Rd P Dolores, Colorado 81323`

To:
`4634 Simms St. Wheat Ridge, CO 80033`

Please have a look at TaxJar's guide on Colorado sales tax here:
https://www.taxjar.com/states/colorado-sales-tax-online/#how-to-collect-sales-tax-in-colorado

Since these addresses are in different tax districts, you do not apply the tax rate of the destination. You would only collect the what they refer to as the "retailer's use tax".

After checking the addresses that you provide, the tax calculations between them seem to be correct based on current rates.

**Comment by c-shultz** [comment] 2020-09-28 18:02
Thanks for looking into this one, @FreshPhil! It sounds like we should be able to close this one from what I'm reading. Do you agree?

**Comment by asuh** [comment] 2020-09-28 20:21
Let me review what @FreshPhil wrote and reply soon. 

The 2nd part of this issue is that we've run into at least one or two Paypal-paid orders with different tax amounts than WooCommerce displayed. This is what tipped us off on the original tax issue.

**Comment by FreshPhil** [comment] 2020-09-29 01:14
Agreed, @c-shultz.

@asuh if you find a different issue with taxes and your payment gateway, I would first recommend trying to reproduce using one of the built in payment methods (Direct Bank Transfer, Cash on Delivery, or Check). That way you can determine if there is an issue with the payment gateway plugin you are using.

If you find a problem that you are able to reproduce, please open up a new issue and let us know.

**Closed by FreshPhil** 2020-09-29 01:14 UTC
Labels: Taxes, [Pri] High, [Status] Needs Author Reply, [Type] Bug
