### ISSUE TITLE
Allow renaming of service names

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#1418] opened 2018-05-24 16:15 UTC
The USPS Shipping method plugin allows renaming of service names, however this plugin doesn't.

![Screenshot](http://joelwills.com/2TE7g2+)

Link to image: http://joelwills.com/2TE7g2

It would be great to be able to allow the same re-naming of services in the WooCommerce Services plugin to be able to simplify the names shown to customers. 

![Screenshot](http://joelwills.com/O3gwf1+)

Link to image: http://joelwills.com/O3gwf1

1174198-zen

**Comment by v18** [comment] 2018-06-06 15:28
@joelwills - hey do you happen to know if there's a pattern in terms of what people want to rename services as? For example, if there's something common like "Priority Mail", we can make that change to please most people quicker. h/t @jeffstieler for this idea

**Comment by joelwills** [comment] 2018-06-06 15:56
In the current USPS plugin you can call a service whatever you want. Some people like to offer two speeds and rename them to "Standard" and "Expedited". Others "1 - 2 working days" and "3 - 5 working days" etc - all sorts of things. 

I've seen people just change it to "USPS", or "VIP shipping".

**Comment by v18** [comment] 2018-06-06 17:23
Thank you 🙏 Doesn't sound like there's one popular option that we should use.

**Comment by dechov** [comment] 2018-06-15 17:43
Closing as duplicate of https://github.com/Automattic/woocommerce-services/issues/1251 – thanks for reporting with ticket reference and for the comparison with USPS Shipping Method.

**Closed by dechov** 2018-06-15 17:43 UTC
Labels: UI / UX, [Type] Enhancement
