### ISSUE TITLE
Tax not applied to UK customers 

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2007] opened 2020-04-21 17:32 UTC
Originally from https://github.com/woocommerce/woocommerce/issues/24354#issuecomment-600573746. 

## Summary
it is reported that WCS is now not applying the tax to any newly registered UK customers regardless of whether a single or 2 worded county is entered, it's applying it to UK customers registered prior to the update on the 11th March but not to any registered after that date.

**Comment by frosso** [comment] 2021-04-19 22:05
Created a brand new site, UK-based.

Created an order through the backend, brand new customer, tax is added for `West Yorkshire`: https://d.pr/i/DDtORe
Created another order through the frontend, brand new customers, tax is calculated for `West Yorkshire`: https://d.pr/i/3ENkUa
Cleaned tax rates table.
Created another order through the frontend, brand new customer, tax is calculated for `West Yorkshire`: https://d.pr/i/ElY6zD

Tried the same steps with taxes manually entered in the backend. If the "State Code" column is updated on a row, WCS&T will automatically create a new row with empty state code when an order is calculated. It will then use this new row for the calculation.

Overall I cannot reproduce, in all cases I could see the tax added to the order.
I'm guessing it was related to something on the API side?

Closing, but feel free to open a new ticket if there are more reports with more detailed steps to reproduce (with from/to addresses).

**Closed by frosso** 2021-04-19 22:05 UTC
Labels: Taxes, [Pri] High, [Type] Bug

**Comment by frosso** [comment] 2021-04-20 17:21
Forgot to mention (and I think it's worth mentioning here - the team already received an email about it): the ticket referred in the description also speaks about how the islands of Guernsey and Jersey have a 0% tax rate.
I inquired TaxJar about these scenarios, to which they replied:

> Based on the country, we can provide a simple calculation but we don't have proper functionality for true VAT calculations (such as sourcing, non-standard rates by product category, reverse charge mechanism, input tax credit support, recoverability, etc.) since much of VAT depends on who the user is (B2B or B2C) and registration status of that customer.
> Rest assured, we have created a feature request for our customers who have requested support in this area.

So the plugin will still present the UK tax rate when billing to the islands of Guernsey and Jersey.
