### ISSUE TITLE
Bad request error for taxes on $0 order

### ISSUE THREAD

**Issue by rynaldos** [Automattic/woocommerce-services#1433] opened 2018-06-07 06:13 UTC
Howdy! 

The following error came up for an order that had a $0 charge: 

`06-03-2018 @ 21:08:40 - Error retrieving the tax rates. Received (400): {"error":"Bad Request","detail":"No amount or line items provided","status":400} (WCS Tax)`

It's likely the default behavior, but for a $0 charge we shouldn’t be making a call to Taxjar?

Thanks!

**Comment by allendav** [comment] 2019-01-10 16:39
If the non-empty cart (and shipping) total is $0, let's not do a taxes look-up. Whoever tackles this issue should first confirm whether or not this is happening.

**Comment by tommyshellberg** [comment] 2020-10-21 10:38
I cannot reproduce this any longer, if you could please try to reproduce this again @rynaldos it would be much appreciated. The logic for short-circuiting the TaxJar API request is here:

https://github.com/Automattic/woocommerce-services/blame/2ac10740744cc5330b96d3f0eebfa676e74a4c0d/classes/class-wc-connect-taxjar-integration.php#L839

The plugin will skip the API request if one of the following is true:

1. Billing country is empty
2. Billing ZIP is empty
3. Order is VAT exempt
4. The line items in the order is empty AND there is a 0 shipping amount.

In this case, number 4 is evaluating to `true` because `$line_items` is an empty array. It appears that zero amount line items are not included in the `$line_items` array. 

I'm going to close this out since it's no longer reproducible and it looks like the code handles this case; if you can provide exact steps to replicate please re-open. :)

**Closed by tommyshellberg** 2020-10-21 10:38 UTC
Labels: Taxes, [Type] Enhancement, [Type] Good First Change
