### ISSUE TITLE
[Bug] Fees are added twice - plugin woocommerce-payment-gateway-based-fees

### ISSUE THREAD

**Issue by InoPlugs** [Automattic/woocommerce-services#1371] opened 2018-04-08 10:53 UTC
Hi,

We are the authors of https://github.com/woocommerce/woocommerce-additional-fees.

Our plugin works fine with the standard tax calculation of WC.

Recently we got a problem reported by a user (WooTheme support ticket) of our plugin that the fees are added twice when this plugin is active:

Customer Email
        vitaly@littlelabradoodle.com <mailto:vitaly@littlelabradoodle.com> 

Customer Name
        littlelabradoodle

Ticket Web Site
        https://littlelabradoodle.com/product-category/available-puppies/

I do not want to publish login credentials here - so please contact me support@inoplugs.com or the user.

When you deactivate jetpack our plugin works correct again.

-----

As this is a rather new feature for WC (and will probably be used often in future) I think we should try to find the solution to keep our plugins compatible - please help.

-----

File woocommerce-additional-fees\classes\class-wc-add-fees.php:

The fees are added using filter woocommerce_calculated_total (or woocommerce_cart_calculate_fees for fees of a single product - but this is not the reason in this case).

- Do you have an idea why this happens
- Can you give me some help how to locate and fix the problem
- As we also need tax calculation for fees: How can I access the tax rate applicable from your plugin
- Not being very familiar with jetpack - how can I debug with Jetpack on localhost (not reachable from outside)

Thank you in advance

Günter / InoPlugs

**Comment by InoPlugs** [comment] 2018-04-18 07:44
Hi,

Any response ?????

WooThemes customer is asking for a solution !!

**Comment by jeffstieler** [comment] 2018-06-04 16:08
Hello @InoPlugs,

My apologies for the delay in response to this issue, and thank you for creating it. 🙇 

> Do you have an idea why this happens

It's likely caused by our integration (ported from TaxJar) directly manipulating the WC Cart object: https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-taxjar-integration.php#L307

> Can you give me some help how to locate and fix the problem

As linked above, here's our tax integration: https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-taxjar-integration.php

Also, we have a pending PR that updates the integration to TaxJar's 1.7.0 plugin version that you should test with: https://github.com/Automattic/woocommerce-services/pull/1398

> Not being very familiar with jetpack - how can I debug with Jetpack on localhost (not reachable from outside)

We use [ngrok](https://ngrok.com/) to make our development environments accessible externally just for the purpose of connecting Jetpack.

**Comment by laurendavissmith** [comment] 2019-10-01 14:54
Closing for now, let us know if its still an issue and we need to reopen it

**Closed by laurendavissmith** 2019-10-01 14:54 UTC
Labels: REPORTED BY USER, Taxes, [Type] Bug, [Type] Help Request
