### ISSUE TITLE
Regional Rates not being pulled by the extension

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-services#2184] opened 2020-09-16 08:17 UTC
I'm unable to retrieve the Regional Rate box A via [WooCommerce Services](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) even though it does show up in [USPS calculator](https://postcalc.usps.com/Calculator/MailServices?country=0&ccode=US&oz=47905&omil=False&dz=36701&dmil=False&mdt=9%2F16%2F2020&mdz=12%3A29&m=6&o=14.5):

![https://d.pr/i/aXj2Dg+](https://d.pr/i/aXj2Dg+)

1. **Shipping from:** 47905
2. **Shipping to:** Gulf Shores, AL 36701

3. **Product:**
    ![https://d.pr/i/r1KJs3+](https://d.pr/i/r1KJs3+)

4. **Configuration:**  Only 4 methods enabled:

    ![https://d.pr/i/1vm3RI+](https://d.pr/i/1vm3RI+)
5. **Package:** 

    ![https://d.pr/i/3A6Lfq+](https://d.pr/i/3A6Lfq+)

I have commercial prices set up as per [this GH comment.](https://github.com/Automattic/woocommerce-services/issues/1349#issuecomment-588242716)

Accessing the checkout page results in this error:

![https://d.pr/i/Q6z77L+](https://d.pr/i/Q6z77L+)

---

The above findings are from my own test site.

**Customer Report**

3309644-zen where they have a slightly different configuration, but product dimensions are same, and no shipping rates returned for Regional Rate box A

Another report in https://wordpress.org/support/topic/estimate-shipping-for-usps-regional-flat-rate-box-options-no-longer-works-fails/#post-13540426

**Comment by elmills** [comment] 2020-10-05 00:03
Is there any testing or issue research support I can provide?  

This issue continues to be a serious roadblock for my business an dis costing sales/impacting the customer experience.  I am unclear what the normal target is for Pri High issues, but would be helpful to understand so I can determine if switching software for shipping may be a faster resolution to the issue.

**Comment by slowbrandon** [comment] 2020-10-12 17:53
Thank you all for the support/assistance!

In response to the closing of the issue on wordpress forums, I have verified this issue has not been "resolved".  

In regards to process, perhaps (minimally) it can be left open till it is actually resolved?  and updates be confined to github thread?  Unfortunately, this is rather misleading to most folks!  However, things are not so simple and maybe reasonable...

To re-iterate the location of the issue is NOT (by my understanding) with the woocommerce-services plugin but in a service/api it is using to obtain the usps estimate/data.

Is the right service/component being targeted for troubleshooting/resolution? Based on my "novice" understanding of the plugin,  rates are quoted from "https://api.woocommerce.com/"?  Have the contributors responsible for that component been contacted?  How can this be done?  Is component open source and available for public inspection/review?  Please provide info.

I would like to assist as well as understand the process.  Thank you!

Regards,
Brandon

**Closed** 2021-11-19 09:47 UTC
Labels: [Type] Bug, [Pri] High
