### ISSUE TITLE
Stripe: Statement Descriptor incorrectly set to "Sandbox"

### ISSUE THREAD

**Issue by pmaiorana** [Automattic/woocommerce-services#1186] opened 2017-10-12 22:36 UTC
For users coming through the new account setup flow for Stripe, the Statement Descriptor is currently being set to "Sandbox", which obviously isn't helpful for customers attempting to identify what this charge is (which is the purpose of this field).

We should change the default to use `Site Name` instead.

<img width="665" alt="screen shot 2017-10-12 at 6 31 48 pm" src="https://user-images.githubusercontent.com/194155/31522475-e96ea1e2-af7b-11e7-97fd-c1dd22931b9b.png">

**Comment by dechov** [comment] 2017-10-13 21:26
Can't seem to reproduce — it's being set to the name of the site (i.e. [`get_bloginfo( 'name' )`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/54edfdfeb88fdeaafd8048534bebd14bd0f301d8/includes/class-wc-stripe-apple-pay.php#L108)) for me:

<img width="669" src="https://user-images.githubusercontent.com/1867547/31567001-3cc9c492-b03b-11e7-9cee-cd9e89b55e79.png">

Does this happen even if you change your site title right before going through the flow?

**Comment by jeffstieler** [comment] 2017-10-13 22:22
Whoops! Looks like @pmaiorana and I were mistaking the site title from https://poopy.life as a Stripe default. Closing.

**Closed by jeffstieler** 2017-10-13 22:22 UTC
