### ISSUE TITLE
Shipping Tax is ignored on additional tax classes

### ISSUE THREAD

**Issue by raifd** [Automattic/woocommerce-services#2624] opened 2023-01-15 07:20 UTC
**Bug description**

When `Automated taxes` are enabled shipping tax is ignored for all additional tax classes despite the address being outside of the tax nexus, not having a rate under Standard Rates,  and having a rate under an additional tax class.

**To Reproduce**

1. Create a store with an address in Washington _(or any other state)_
2. Enable automated taxes
3. Create additional tax class _(Special Rates)_
4. Add a tax rate for California _(or any other state except the tax nexus - Step 1)_ **(under Special Rates)** 
5. Create a new product
6. Choose **Special Rates** as the **tax class** under **Product Data > General**
7. Add the product to the cart
8. Tax is being calculated only on the product price - shipping tax is ignored

**Screenshots from the steps to reproduce:**

- Step 3: 
![Annotation on 2023-01-15 at 08-12-55](https://user-images.githubusercontent.com/23462281/212527989-9f5525d4-96ca-4e30-af56-dc8db0f0b416.png)

- Step 4: ![Annotation on 2023-01-15 at 08-07-43](https://user-images.githubusercontent.com/23462281/212527880-0808a201-8804-4b81-bc4e-6cbbd03f12f6.png)

- Step 6: 
![Annotation on 2023-01-15 at 08-14-13](https://user-images.githubusercontent.com/23462281/212528034-2c6fcfeb-a2b6-4f49-a7a3-099128dc7885.png)

**Expected behavior**

The expected behavior in this instance is that shipping tax is calculated if:

1. The address is not within the tax nexus
2. No standard rates are present 

This issue was discussed in Slack here: p1673511805586719-slack-C7U3Y3VMY

**Comment by AashikP** [comment] 2023-01-16 03:13
Merchant reports:

5841555-zen

**Comment by iyut** [comment] 2023-01-19 07:27
Hi,
I did some digging and testing on this issue. Based on my testing, I don't think this is a bug.
When we set the tax to be automatic, the plugin will overwrite the tax value on any tax classes that being set in the product based on response from TaxJar API.
I tried to confirm this by following the steps in the description and here is the result :
1. The Special Rates table in WC Settings will be overwritten by TaxJar.
2. The shipping checkbox in tax table will also be checked automatically by TaxJar if the shipping in the current state is taxable. Here is the article about [States where shipping is taxable](https://www.taxjar.com/sales-tax/sales-tax-and-shipping).

I also have tried to digging a bit into the code and found out it has been designed this way by [this code](https://github.com/Automattic/woocommerce-services/blob/b1294f846e420663e9c0c913138c018e6a4f8d9b/classes/class-wc-connect-taxjar-integration.php#L1119-L1136).

**Screenshots :** 
Before the calculation in cart/checkout page : 
<img width="999" alt="Screenshot 2023-01-18 at 19 33 43" src="https://user-images.githubusercontent.com/631098/213380854-7dace683-4647-4166-bafe-61761751de6c.png">

After the calculation : 
<img width="1051" alt="Screenshot 2023-01-18 at 20 03 50" src="https://user-images.githubusercontent.com/631098/213380882-5cb2e1d4-c7eb-4f96-a133-f753a51f7005.png">

Can you also try to test and confirm if the "Special Rates" is being overwritten on your end?

**Comment by usisu** [comment] 2023-01-19 19:41
The bug applies to other states not the state with nexus in the Standard tax class, i.e. the Additional tax class states not overwritten by Taxjar. All Additional tax classes rates are not being applied to shipping, only to the products. A store can have nexus in more than one state. Shipping tax only works on the state rates being overwritten by Taxjar while Automated taxes are turned on. This is the expected behaviour for the Additional tax classes shipping tax: https://woocommerce.com/document/setting-up-taxes-in-woocommerce/#shipping-tax-class

**Comment by iyut** [comment] 2023-01-20 07:19
> The bug applies to other states not the state with nexus in the Standard tax class, i.e. the Additional tax class states not overwritten by Taxjar.

I did testing for other states as well. From DC -> CA, with "Special rates" tax class is applied to the product. I can see that the "Special rates" tax class is still being overwritten.

DC Store Address Screenshot : 
<img width="670" alt="Screenshot 2023-01-20 at 09 30 32" src="https://user-images.githubusercontent.com/631098/213632195-ba1f8b80-56a8-4403-98ba-755040eb27c0.png">

Product tax class setting : 
<img width="841" alt="Screenshot 2023-01-20 at 09 31 37" src="https://user-images.githubusercontent.com/631098/213632615-816b1076-77ff-4722-883e-96a5d7e809b0.png">

Special Rate tax class setting ( before being overwritten ) : 
<img width="1326" alt="Screenshot 2023-01-20 at 13 33 59" src="https://user-images.githubusercontent.com/631098/213632660-61f914b7-da42-4424-8d3f-b60307607ecb.png">

Cart Address to CA : 
<img width="472" alt="Screenshot 2023-01-20 at 13 37 02" src="https://user-images.githubusercontent.com/631098/213632957-d0ccb251-8891-413b-a0de-ee0ef934700a.png">

Special Rate tax class setting ( after being overwritten ) : 
<img width="1326" alt="Screenshot 2023-01-20 at 13 36 38" src="https://user-images.githubusercontent.com/631098/213633089-275968a4-fb8d-496c-b3a7-e97c39f54de8.png">

In the last screenshot, you see that the "Shipping" tax is not being applied. It is due to TaxJar thinks that California state doesn't apply tax for the shipping. Here is [the article](https://www.taxjar.com/sales-tax/sales-tax-and-shipping) about it.

From what I see here, the shipping tax is being ignored in additional tax class is because the TaxJar thinks that the state doesn't apply tax for shipping and the current additional tax class setting will be overwritten by TaxJar response.

Hopefully I didn't miss something. But please let me know if I miss something here.

**Comment by AashikP** [comment] 2023-01-20 11:32
Thank you for sharing those details, @iyut 

I understand the article from TaxJar and I'd completely agree if we're talking about [TaxJar](https://woocommerce.com/products/taxjar/?aff=10486&cid=1131038) here. 

That said, I have two follow-up questions here:

1. [Automated Tax Calculation - Documentation](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#automated-tax-calculation) states:

    > When Automated taxes are in use, this overrides any tax rates you have manually added **for locations where you have a tax nexus**, as well as the “Compound” and “Shipping” toggles for those tax rates.

2. The code [you linked to](https://github.com/Automattic/woocommerce-services/blob/b1294f846e420663e9c0c913138c018e6a4f8d9b/classes/class-wc-connect-taxjar-integration.php#L1120): `$tax_class = $product->get_tax_class();`


**Regarding `#1`:**

[Automated Taxes do not appear to be calculating - Documentation](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#automated-taxes-do-not-appear-to-be-calculating) says:

> You can also have a tax nexus in another state if you exceed a certain yearly dollar value or order total to another state. If you are unsure of your tax nexus status, please consult a certified local accountant.

> If you need to charge tax for any other state, you can add a [tax rate](https://woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-12) for that state in addition to using automated taxes to charge customers from that state tax as well.

So, since [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) does not manage those tax rates, it should also not decide if shipping should be taxed or not for locations outside of the store location / what it thinks as a nexus, correct?

**Regarding `#2`**

I would assume that the extension is checking if there is a specific tax class assigned to the product and grabbing details from that tax class. So ideally it should respect that tax class?

Or is my understanding about that particular line incorrect?

**Comment by maxlaf** [comment] 2023-01-24 02:30
I'm wondering if this is actually the expected behaviour here. When automated taxes are enabled, the Shipping tax class is set to "Standard" and cannot be changed:

![ZZC9sF.png](https://user-images.githubusercontent.com/56649567/214199052-3478981b-ddd4-418a-8f71-33668858b901.png)

If a product uses a different tax class, automated taxes are still calculated for the tax nexus and are written to whichever tax class the product is set to. For taxes outside of the nexus, the product uses any rates in the specified tax class. If a product uses a tax class other than Standard, shipping will not be taxed unless a rate is entered in the Standard rates as well.

![Gvnbhf.png](https://user-images.githubusercontent.com/56649567/214200013-4843c484-4ff0-41e3-a899-a0b1dfb939b8.png)

![yzddjd.png](https://user-images.githubusercontent.com/56649567/214200070-366e22a0-1e30-4543-839b-a9ed84ae7128.png)

![fCHD5f.png](https://user-images.githubusercontent.com/56649567/214200110-63094e51-f1c3-4c5c-b2b6-d3c2fccdb03c.png)

![oJHc25.png](https://user-images.githubusercontent.com/56649567/214200328-540ce3da-551c-41d8-89af-157c9408c804.png)

I might be missing something here, but since the shipping tax class cannot be changed to "Based on cart items" when automated taxes are enabled, it seems that taxes must be entered in the Standard rates for any out-of-nexus states that need to calculate tax on shipping.

**Comment by usisu** [comment] 2023-01-24 06:53
In this example if you remove CA from the standard tax class, tax won't be
charged for CA. Say the store has nexus in TN and wants to charge tax on
shipping using an additional tax class, it won't work with automated taxes
turned on. TN should not have to be added to the standard tax class to tax
shipping.

**Comment by raifd** [comment] 2023-01-24 07:26
@maxlaf I was wondering whether this is expected too however if it was, then no taxes should be calculated if the address is outside of the nexus. Here is an example:

**Store Address (nexus):** Vancouver, Washington 
**Standard Rates:** Empty as seen below
![Annotation on 2023-01-24 at 08-21-26](https://user-images.githubusercontent.com/23462281/214233549-f3f90d6c-c624-489a-b2e2-2e81c9ff9271.png)
**Special Rates:** One single entry for California - 10% tax
![Annotation on 2023-01-24 at 08-22-26](https://user-images.githubusercontent.com/23462281/214233735-a5c2bc49-52c9-4f75-bb79-f2e1470825e7.png)
**Product Tax Class:** Special Rates
![Annotation on 2023-01-24 at 08-23-23](https://user-images.githubusercontent.com/23462281/214233856-e8324a78-9ead-4a29-9add-63dbdf62632a.png)

With all the above, during the checkout tax is applied only to the product's price and not to shipping. If the extension would work only for the nexus, in that case, no tax should be applied - even that to the product. 
![Annotation on 2023-01-24 at 08-24-21](https://user-images.githubusercontent.com/23462281/214234113-6ffd6a0e-1ca9-407f-b4aa-a9ae9707ae6f.png)

**Comment by AashikP** [comment] 2023-01-24 07:30
Cross-checking again as per @usisu (https://github.com/Automattic/woocommerce-services/issues/2624#issuecomment-1401466828), I agree this looks like expected behavior, and not a bug:

![ltMYO2.png](https://user-images.githubusercontent.com/17475174/214234773-e57ee052-6232-419d-93cc-9d689f14714b.png)

Especially `Shipping Tax` is locked to the Standard Tax class.

**Comment by raifd** [comment] 2023-01-24 07:37
@AashikP Hmm yes, I only now notice that the `Shipping tax class` is locked to `Standard`. In that case, I believe this is expected too but I am not sure why is tax charged at all.

**Comment by AashikP** [comment] 2023-01-24 07:41
> but I am not sure why is tax charged at all.

My understanding is that it is because the additional tax rates are one of the two sections that is not locked:

![hUbD22.png](https://user-images.githubusercontent.com/17475174/214236463-5d9c995c-2493-4059-9f73-c67543202337.png)

Based on that, my understanding is that:

1. You can have additional tax classes for Products
2. Shipping tax is still locked to Standard rates

**Comment by iyut** [comment] 2023-01-24 12:17
> So, since [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) does not manage those tax rates, it should also not decide if shipping should be taxed or not for locations outside of the store location / what it thinks as a nexus, correct?

Yes, I believe this is the case.

> I would assume that the extension is checking if there is a specific tax class assigned to the product and grabbing details from that tax class. So ideally it should respect that tax class?

Yes, the response from TaxJar will be applied to the respected tax class.

**Comment by iyut** [comment] 2023-02-01 07:07
Hi all,
From what I see on our discussion, it seems the issue is not a bug? And if it's not a bug, should we close this issue?

**Comment by AashikP** [comment] 2023-02-01 07:55
That indeed seems to be the case unless we're missing something here. I'd say we close this and we can re-open again if we did miss some fact!

**Comment by iyut** [comment] 2023-02-01 12:03
Yes sure, I'll close this issue then. Please don't hesitate to re-open this issue if someone think otherwise.

**Closed as completed by iyut** 2023-02-01 12:03 UTC
Labels: [Type] Bug, [Pri] High
