### ISSUE TITLE
[WC 4.4 beta1] Create shipping label notice layout is a bit cramped 

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#2106] opened 2020-07-29 21:15 UTC
**Description:**

The message, the `Create shipping label` button and the close icon of the `Create shipping label` notice on the order page feel a bit cramped:

![services](https://user-images.githubusercontent.com/19143190/88853682-197f8380-d1be-11ea-96bd-4ebacf5bdc16.jpg)

**Steps to reproduce:**

I tested using WooCommerce 4.4 beta1 and WordPress 5.5-RC1-48681. 

1. Start OBW.
2. Enter the US address in the `Store details` section during OBW. 
3. On the `Tell us about your business` page, select checkbox next to `Install recommended free business features` so that WC Services could be installed. 
4. Complete OBW.
5. Place an order on the site. 
6. Navigate to the order page and see the notice letting you know that you can create a shipping label with the cramped layout. 

**Expected behavior:**

I think more space (padding) between the text, button, and the exit icon will make it for a nicer experience. Alternatively, the `Create shipping label` button can be placed under the message and centered. 

**Environment:**  

OS: macOS Catalina 10.15.5
Browser: Chrome 84.0.4147.89 (Official Build) (64-bit)

**Comment by c-shultz** [comment] 2020-07-29 22:44
Thanks for the report! Just a note that the fix for this will be in the wc-admin repo. We'll plan on taking care of it.

**Comment by juliaamosova** [comment] 2020-07-29 23:14
Sounds good, thanks @c-shultz!

**Comment by elizaan36** [comment] 2020-07-30 15:41
Yeah, I noticed this in the past couple days as well, thanks for creating this issue. Not sure if something's changed since the prompt was released.🤔

We'll have to tweak the layout of the prompt a bit because there needs to be fixed padding between the text, button, and close icon. Keeping in mind smaller screen sizes as well.

In addition to the expected behavior notes Julia shared above, here the primary action should stay fixed on the right of the card rather than moving with the text.
<img width="1802" alt="Screen Shot 2020-07-24 at 11 00 58 AM" src="https://user-images.githubusercontent.com/5121465/88941651-e5a06e80-d24e-11ea-99d2-0e2ef36d8cc1.png">

Here the close icon shouldn't overlap the button:
<img width="674" alt="Screen Shot 2020-07-24 at 11 19 03 AM" src="https://user-images.githubusercontent.com/5121465/88941712-f81aa800-d24e-11ea-8ace-eb22efd3d486.png">

**Comment by harriswong** [comment] 2020-08-04 18:08
@elizaan36 Do we also need to change the "Create shipping label" blue button to red?

**Comment by elizaan36** [comment] 2020-08-04 19:05
No, it's blue here because it's in the wp-admin view so the button should be consistent with WordPress elements.

**Comment by harriswong** [comment] 2020-08-04 23:43
Here is how it would look like after the patch:

![image](https://user-images.githubusercontent.com/572862/89355906-c3a55280-d679-11ea-8cb5-953ac774cda3.png)
![image](https://user-images.githubusercontent.com/572862/89355937-d3bd3200-d679-11ea-8374-ba2d90512674.png)
![image](https://user-images.githubusercontent.com/572862/89355986-f18a9700-d679-11ea-8893-0935cf55edf9.png)
![image](https://user-images.githubusercontent.com/572862/89356012-fe0eef80-d679-11ea-89ec-cb8dd027e0d2.png)

**Comment by harriswong** [comment] 2020-08-04 23:46
Mouse over the button will result:
![image](https://user-images.githubusercontent.com/572862/89356162-580fb500-d67a-11ea-92ed-bc95ffbd63fd.png)

I am going to remove this red hover as well.

**Comment by elizaan36** [comment] 2020-08-05 14:08
Looks perfect Harris, except one small thing. Can we move the text down so the padding is equal top and bottom to make the text vertically centered in the card. Thinking about the error message if there is one, it should move the other text up so that it's always vertically centered.

This is what the padding looks like now:
<img width="94" alt="Screen Shot 2020-08-05 at 9 03 33 AM" src="https://user-images.githubusercontent.com/5121465/89422444-f7748c80-d6fa-11ea-8ffc-860d3f648789.png">
Should be equal top and bottom for all the elements in the banner, including illustration, text, and actions.

Great about removing the red hover state.

**Comment by harriswong** [comment] 2020-08-06 20:30
@elizaan36 I have updated the margins/paddings to make the text vertically aligned. Removed the hover red effect. Also the error message is aligned.

![image](https://user-images.githubusercontent.com/572862/89578691-c7f37c00-d7ef-11ea-8102-3a31e405e66a.png)
![image](https://user-images.githubusercontent.com/572862/89579373-e6a64280-d7f0-11ea-96c2-369554edb0d1.png)
![image](https://user-images.githubusercontent.com/572862/89579402-f3c33180-d7f0-11ea-8c8c-4c70f8ce2095.png)
![image](https://user-images.githubusercontent.com/572862/89579432-fde53000-d7f0-11ea-9736-c96136b580f4.png)
![image](https://user-images.githubusercontent.com/572862/89579571-38e76380-d7f1-11ea-88a9-256cf1aa8c0f.png)

**Comment by harriswong** [comment] 2020-08-06 20:40
Created an issue(https://github.com/woocommerce/woocommerce-admin/issues/4938) in woocommerce-admin to track. 
Created a PR in `woocommerce-admin` repository: https://github.com/woocommerce/woocommerce-admin/pull/4948.

**Comment by harriswong** [comment] 2020-08-07 15:19
Merged. Closing.

**Closed by harriswong** 2020-08-07 15:19 UTC
Labels: [Pri] High, [Type] Bug, [Type] Good First Change
