### ISSUE TITLE
Verify customer selected shipping box still shows with UPS and USPS extension

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2137] opened 2020-08-13 16:58 UTC
### Description
The customer select shipping green box should display the shipping rates and shipping method when using the [UPS](https://woocommerce.com/products/ups-shipping-method/) and [USPS extensions](https://woocommerce.com/products/usps-shipping-method/).
![image](https://user-images.githubusercontent.com/572862/90163605-8ca6ff00-dd53-11ea-8f85-a52dc6b1f1d2.png)

### Outcome
- Verify these two extensions are compatible with the greenbox text
- If it doesn't work and effort is low (1-2 days?), fix the issue. Otherwise, create a separate issue to address this compatibility.

**Comment by harriswong** [comment] 2020-08-13 16:59
Relates to https://github.com/Automattic/woocommerce-services/issues/2116

**Comment by frosso** [comment] 2020-08-18 21:55
RESULTS:

- Tested WCS with UPS (both live rates and with fallback value)
  - Working as expected
  - Paid amount is correctly displayed in the backend
- Tested WCS with USPS
  - Only tested with fallback value (live rates weren't working for me at the time, probably due to some configuration issues - talking with @c-shultz we have high confidence that it would still be working fine)
  - Paid amount is correctly displayed in the backend

UPS:
![Screen Shot 2020-08-18 at 4 43 47 PM](https://user-images.githubusercontent.com/273592/90569532-a68d7b00-e173-11ea-9f90-323ae9ee2e68.png)


USPS:
![Screen Shot 2020-08-18 at 4 47 14 PM](https://user-images.githubusercontent.com/273592/90569491-95446e80-e173-11ea-819d-bfbd73142173.png)


Overall: ✅

**Comment by c-shultz** [comment] 2020-08-18 22:12
I was doing some WCS testing already so I tried USPS and confirmed that it's coming through OK as well:
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/6209518/90570676-11838580-e165-11ea-9ab7-88dc31df858c.png">

**Comment by c-shultz** [comment] 2020-08-18 22:27
Thanks for testing this, @frosso! Looks like we're good on this so I'll close it out.

**Closed by c-shultz** 2020-08-18 22:27 UTC
Labels: [Type] Compatibility, [Type] Task
