### ISSUE TITLE
Test with PHP versions 7, 7.1

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1005] opened 2017-05-09 01:50 UTC
We should run our tests on PHP 7.0 and 7.1 (latest versions): https://github.com/Automattic/woocommerce-services/blob/master/.travis.yml

Related: p6q8Tx-BE-p2

**Comment by jeffstieler** [comment] 2018-02-13 22:55
Duplicate of https://github.com/Automattic/woocommerce-services/issues/780, closing.

**Closed by jeffstieler** 2018-02-13 22:55 UTC
