### ISSUE TITLE
Rename "Packages" tab to avoid confusion with ASP "Packages" tab 

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#1162] opened 2017-09-25 17:26 UTC
Currently, if a user has WC Services activated and also using [Advanced Shipping Packages](https://docs.woocommerce.com/document/woocommerce-advanced-shipping-packages/) extension, the Shipping menu has 2 identical tabs called **Packages** next to each which is confusing:

![](https://cloudup.com/cXicgDDoic0+)
Image Link: https://cloudup.com/cXicgDDoic0

**ADVANCED SHIPPING PACKAGES** tab looks as follows:

![](https://cloudup.com/cSXJ8uCJYVd+)
Image Link: https://cloudup.com/cSXJ8uCJYVd

**WC SERVICES** tab looks as follows:

![](https://cloudup.com/cWwrlGJ5T7q+)
Image Link: https://cloudup.com/cWwrlGJ5T7q

I see 3 solutions here:

1. We can rename WC Services Packages section to something like "Services Packages"
2. Developers of Advanced Shipping Packages extension could rename their tab to something like "Advanced Packages"
3. Both Packages settings would be displayed under the same tab called "Packages" but will have different Sections (similar to how VAT settings section is being added to the general Tax section upon VAT Number extension activation).

**Comment by dechov** [comment] 2017-09-25 17:29
Duplicate of https://github.com/Automattic/woocommerce-services/issues/1110 (though detailed report and suggestions are appreciated!)

**Comment by juliaamosova** [comment] 2017-09-25 17:32
@dechov my bad, didn't look thorough enough for currently open issues related to Packages tab. Thanks for pointing out!

**Comment by jeffstieler** [comment] 2018-02-21 20:54
I kind of like both options 1 and 2 - "packages" isn't really a fitting label for both plugins.

For Advanced Shipping Packages - how about "Package groups", "Package splitting", or "Advanced Shipping Packages"?

For WCS - how about "Package types", "Custom packaging", or "Packaging"?

**Closed** 2018-05-03 10:15 UTC
Labels: Packages and Packing, [Status] Needs Author Reply, [Type] Enhancement
