### ISSUE TITLE
"Only give them the one, cheapest rate." checked but still gives multiple results

### ISSUE THREAD

**Issue by andygarylee** [Automattic/woocommerce-services#986] opened 2017-04-15 00:47 UTC
On "Rates to show customer" I have "Only give them the one, cheapest rate." selected. 

However, I still get multiple options from the plugin, and selecting and unselecting does not make a difference.

Help?

**Comment by DanReyLop** [comment] 2017-04-15 06:57
Hi Andy,

`Only give them the one, cheapest rate` will give the customer only one rate **from the configured shipping method**. So, for example, if you have in the `USA` Shipping Zone these shipping methods configured:
* Flat rate
* FedEx (from another plugin)
* USPS (WooCommerce Services)

The customer will only receive 1 rate from `USPS`, but will also get options from `FedEx` and `Flat rate` if it applies to his order.

Could you please check if you have that situation? If you disable all the shipping methods except from `USPS (WooCommerce Services)`, do you still have that problem?

**Comment by mdleung** [comment] 2017-11-03 20:10
I can confirm that this problem still exists.

Thanks.

**Comment by jeffstieler** [comment] 2017-11-18 01:35
👋  @mdleung - can you show your shipping configuration?

I am unable to reproduce with only a USPS (WooCommerce Services) method enabled in my shipping zone.

Before:

![screen shot 2017-11-17 at 6 33 27 pm](https://user-images.githubusercontent.com/63922/32975593-f70a6352-cbc5-11e7-8929-df5a0ffdcf42.png)

![screen shot 2017-11-17 at 6 33 45 pm](https://user-images.githubusercontent.com/63922/32975594-fa0dd9ee-cbc5-11e7-8716-e9bc0601bb3e.png)

After:

![screen shot 2017-11-17 at 6 34 01 pm](https://user-images.githubusercontent.com/63922/32975596-020bae82-cbc6-11e7-8e69-3119ed32a8a8.png)

![screen shot 2017-11-17 at 6 34 10 pm](https://user-images.githubusercontent.com/63922/32975598-04e58128-cbc6-11e7-9a83-110a4810c13b.png)

**Comment by jeffstieler** [comment] 2018-02-13 22:26
I tried to reproduce this again, but couldn't - so I'm closing the issue.

@andygarylee @mdleung please re-open this issue if you encounter it again on the latest version of WooCommerce Services (1.11.0 at the time of this writing). Thanks!

**Closed by jeffstieler** 2018-02-13 22:26 UTC
Labels: REPORTED BY USER, [Status] Needs Author Reply, [Type] Help Request
