### ISSUE TITLE
Manage state of the save button in the shipping settings screen

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#2051] opened 2020-06-16 12:14 UTC
As specified in the designs in #2028, the "Save" button at the bottom of the Shipping Settings screen (`/wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`) should be disabled unless `Shipping Labels` or `Packages` cards are modified. Adding new carriers or eliminating existing ones shouldn't affect that button, since it's not required to update the carrier accounts list.

This feature can be implemented independently from the work done here: https://github.com/Automattic/woocommerce-services/pull/2049

**Comment by c-shultz** [comment] 2020-06-16 14:59
Duplicate of https://github.com/Automattic/woocommerce-services/issues/2038

**Closed by c-shultz** 2020-06-16 14:59 UTC
Labels: [Pri] High, [Proj] Carrier Accounts
