### ISSUE TITLE
Missing Global Express Guaranteed for shipping rates.

### ISSUE THREAD

**Issue by tsetend** [Automattic/woocommerce-services#1857] opened 2019-12-17 10:07 UTC
Ticket: 2540627-zen

Issue: The shipping label doesn't give the option for Global Express Guaranteed shipping options. I could replicate this same on my end.

1. Added custom package 

![Screenshot](https://d.pr/i/FNaIqI+)
Screenshot: https://d.pr/i/FNaIqI

2. On creating a shipping label for order doesn't return the Global Express Guaranteed method in shipping rates.

![Screenshot](https://d.pr/i/6bQYCP+)
Screenshot: https://d.pr/i/6bQYCP

3. Tested on USPS shipping rate calculator and could see this option:

![Screenshot](https://d.pr/i/E8xk33+)
Screenshot: https://d.pr/i/E8xk33

WC Version: 3.8.1
WooCommerce Services – 1.22.2

**Comment by tsetend** [comment] 2019-12-24 04:12
The customer got back 2540627-zen to inform them when there is a fix release. They are waiting for the fix to launch the site.

**Comment by dphyled** [comment] 2020-01-21 08:25
Set to High for now so that it has a Priority. If USPS is returning a service, but WCS isn't, seems like `High`, but please adjust if necessary. Thank you! : )

**Comment by dkmyta** [comment] 2020-06-06 16:47
Another report in 3038863-zen for a user attempting to generate a shipping label for an order to India.

**Comment by anant1811** [comment] 2020-06-09 05:15
Another report in 3038863-zen for order to South Africa.

**Comment by aleftick** [comment] 2020-06-09 20:50
EasyPost doesn't support _Global Express Guaranteed_ hence we can't support either. 

It's an international shipping option from the U.S. Postal Service® with international transportation and delivery by FedEx Express.

**Comment by c-shultz** [comment] 2020-06-09 21:25
We have never allowed `Global Express Guaranteed` rates, so this is expected behavior and not a bug. I'm closing this out since we don't have a plan to add this feature.

**Closed by c-shultz** 2020-06-09 21:25 UTC
Labels: [Pri] Low, [Type] Enhancement
