### ISSUE TITLE
Colorado tax rates not added correctly if City does not match the Zip Code

### ISSUE THREAD

**Issue by phillipcornwell** [Automattic/woocommerce-services#1867] opened 2020-01-16 02:09 UTC
A Colorado store sees an incorrect tax rate added to their store by WCS when the wrong city is used with the zip code. The results shown below would be correct if the zip code was correctly set for a Denver address.

![Screenshot](https://d.pr/i/xo4wvC+)
Screenshot direct link: https://d.pr/i/xo4wvC

This was done three more times and each time something incorrect occurred.

![Screenshot](https://d.pr/i/ikL9Gm+)
Screenshot direct link: https://d.pr/i/ikL9Gm

### Tax Logs For Ft. Collins 80521 to "Denver" 80521:
```
[15-Jan-2020 20:49:56 UTC] Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"CO","from_zip":"80521","from_city":"Ft. Collins","from_street":"125 S Howes St","to_country":"US","to_state":"CO","to_zip":"80521","to_city":"Denver","to_street":false,"shipping":"99.90","plugin":"woo","line_items":[{"id":"3437-6df305659ea6942bb219bdc6b1570c44","quantity":1,"product_tax_code":"","unit_price":"999.00","discount":"0"}]} (WCS Tax)
[15-Jan-2020 20:49:58 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.037,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":40.66,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":3.7,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0},"line_items":[{"taxable_amount":999.0,"tax_collectable":36.96,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_tax_collectable":0.0},"amount_to_collect":40.66}} (WCS Tax)
[15-Jan-2020 20:49:58 UTC] :: Adding New Tax Rate :: (WCS Tax)
[15-Jan-2020 20:49:58 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:49:58 UTC] Tax Rate ID Set for 1 (WCS Tax)
[15-Jan-2020 20:49:58 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:49:58 UTC] {"1":{"rate":3.7,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:49:58 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:49:58 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:49:58 UTC] Tax Rate ID Set for 1 (WCS Tax)
```

### Tax Logs for Ft. Collins, 80521 to "Fort Collings", 80521:
```
[15-Jan-2020 20:50:30 UTC] :::: TaxJar Plugin requested :::: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :::: TaxJar API called :::: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"CO","from_zip":"80521","from_city":"Ft. Collins","from_street":"125 S Howes St","to_country":"US","to_state":"CO","to_zip":"80521","to_city":"Fort Collings","to_street":false,"shipping":"99.90","plugin":"woo","line_items":[{"id":"3437-6df305659ea6942bb219bdc6b1570c44","quantity":1,"product_tax_code":"","unit_price":"999.00","discount":"0"}]} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.0755,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US","city":"FORT COLLINS"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":82.97,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":7.54,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.0755,"city_taxable_amount":99.9,"city_tax_rate":0.0385,"city_amount":3.85},"line_items":[{"taxable_amount":999.0,"tax_collectable":75.42,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.0755,"city_taxable_amount":999.0,"city_tax_rate":0.0385,"city_amount":38.46}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.0755,"city_taxable_amount":1098.9,"city_tax_rate":0.0385,"city_tax_collectable":42.31},"amount_to_collect":82.97}} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Adding New Tax Rate :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.55,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Tax Rate ID Set for 2 (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"2":{"rate":7.55,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.55,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Tax Rate ID Set for 2 (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :::: TaxJar Plugin requested :::: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :::: TaxJar API called :::: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.0755,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US","city":"FORT COLLINS"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":82.97,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":7.54,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.0755,"city_taxable_amount":99.9,"city_tax_rate":0.0385,"city_amount":3.85},"line_items":[{"taxable_amount":999.0,"tax_collectable":75.42,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.0755,"city_taxable_amount":999.0,"city_tax_rate":0.0385,"city_amount":38.46}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.0755,"city_taxable_amount":1098.9,"city_tax_rate":0.0385,"city_tax_collectable":42.31},"amount_to_collect":82.97}} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"2":{"rate":7.55,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.55,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Tax Rate ID Set for 2 (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"2":{"rate":7.55,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:50:30 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.55,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:50:30 UTC] Tax Rate ID Set for 2 (WCS Tax)
```

### Tax Logs for Ft. Collins, 80521 to Ft. Collins, 80521:
```
[15-Jan-2020 20:51:18 UTC] :::: TaxJar Plugin requested :::: (WCS Tax)
[15-Jan-2020 20:51:18 UTC] :::: TaxJar API called :::: (WCS Tax)
[15-Jan-2020 20:51:18 UTC] Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"CO","from_zip":"80521","from_city":"Ft. Collins","from_street":"125 S Howes St","to_country":"US","to_state":"CO","to_zip":"80521","to_city":"Ft. Collins","to_street":false,"shipping":"99.90","plugin":"woo","line_items":[{"id":"3437-6df305659ea6942bb219bdc6b1570c44","quantity":1,"product_tax_code":"","unit_price":"999.00","discount":"0"}]} (WCS Tax)
[15-Jan-2020 20:51:18 UTC] PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /srv/htdocs/wp-content/plugins/popup-maker/includes/modules/reviews.php on line 298
[15-Jan-2020 20:51:19 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.037,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":40.66,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":3.7,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0},"line_items":[{"taxable_amount":999.0,"tax_collectable":36.96,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_tax_collectable":0.0},"amount_to_collect":40.66}} (WCS Tax)
[15-Jan-2020 20:51:19 UTC] :: Adding New Tax Rate :: (WCS Tax)
[15-Jan-2020 20:51:19 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:19 UTC] Tax Rate ID Set for 3 (WCS Tax)
[15-Jan-2020 20:51:19 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:51:19 UTC] {"3":{"rate":3.7,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:51:19 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:51:19 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:19 UTC] Tax Rate ID Set for 3 (WCS Tax)
```

### Tax Logs for Ft. Collins 80521 to "Aurora" 80521:
```
[15-Jan-2020 20:51:53 UTC] :::: TaxJar Plugin requested :::: (WCS Tax)
[15-Jan-2020 20:51:53 UTC] :::: TaxJar API called :::: (WCS Tax)
[15-Jan-2020 20:51:53 UTC] Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"CO","from_zip":"80521","from_city":"Ft. Collins","from_street":"125 S Howes St","to_country":"US","to_state":"CO","to_zip":"80521","to_city":"Aurora","to_street":false,"shipping":"99.90","plugin":"woo","line_items":[{"id":"3437-6df305659ea6942bb219bdc6b1570c44","quantity":1,"product_tax_code":"","unit_price":"999.00","discount":"0"}]} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.037,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":40.66,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":3.7,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0},"line_items":[{"taxable_amount":999.0,"tax_collectable":36.96,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_tax_collectable":0.0},"amount_to_collect":40.66}} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Adding New Tax Rate :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Tax Rate ID Set for 4 (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"4":{"rate":3.7,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Tax Rate ID Set for 4 (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :::: TaxJar Plugin requested :::: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :::: TaxJar API called :::: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Received: {"tax":{"taxable_amount":1098.9,"tax_source":"destination","shipping":99.9,"rate":0.037,"order_total_amount":1098.9,"jurisdictions":{"state":"CO","county":"LARIMER","country":"US"},"has_nexus":true,"freight_taxable":true,"breakdown":{"taxable_amount":1098.9,"tax_collectable":40.66,"state_taxable_amount":1098.9,"state_tax_rate":0.029,"state_tax_collectable":31.87,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_tax_collectable":0.0,"shipping":{"taxable_amount":99.9,"tax_collectable":3.7,"state_taxable_amount":99.9,"state_sales_tax_rate":0.029,"state_amount":2.9,"special_taxable_amount":0.0,"special_tax_rate":0.0,"special_district_amount":0.0,"county_taxable_amount":99.9,"county_tax_rate":0.008,"county_amount":0.8,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0},"line_items":[{"taxable_amount":999.0,"tax_collectable":36.96,"state_taxable_amount":999.0,"state_sales_tax_rate":0.029,"state_amount":28.97,"special_tax_rate":0.0,"special_district_taxable_amount":0.0,"special_district_amount":0.0,"id":"3437-6df305659ea6942bb219bdc6b1570c44","county_taxable_amount":999.0,"county_tax_rate":0.008,"county_amount":7.99,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_amount":0.0}],"county_taxable_amount":1098.9,"county_tax_rate":0.008,"county_tax_collectable":8.79,"combined_tax_rate":0.037,"city_taxable_amount":0.0,"city_tax_rate":0.0,"city_tax_collectable":0.0},"amount_to_collect":40.66}} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"4":{"rate":3.7,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Tax Rate ID Set for 4 (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Tax Rate Found :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"4":{"rate":3.7,"label":"CO Tax","shipping":"yes","compound":"no"}} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] :: Updating Tax Rate To :: (WCS Tax)
[15-Jan-2020 20:51:54 UTC] {"tax_rate_country":"US","tax_rate_state":"CO","tax_rate_name":"CO Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":3.6999999999999997,"tax_rate_class":""} (WCS Tax)
[15-Jan-2020 20:51:54 UTC] Tax Rate ID Set for 4 (WCS Tax)
```
## To Duplicate:
1. Ensure all plugins except Jetpack, WC and WC Services are disabled.
2. In **WooCommerce → Settings → Tax tab** ensure **Automated taxes** is set to `Disable automated taxes`. This is so we can flush the current tax rates to show the issue.
3. In the **Standard Tax** section, clear all tax rates.
4. Back in the **Tax Options** section Update the **Automated Taxes** to `Enable automated taxes`
5. Update the store address to:
![Screenshot](https://d.pr/i/xrxOHm+)
Screenshot direct link: https://d.pr/i/xrxOHm
6. Create a new order with the same zip code but an incorrect city like "Denver" or "Aurora" to replicate.

**Comment by phillipcornwell** [comment] 2020-01-16 02:18
Ticket 2635468-zen

**Comment by harriswong** [comment] 2021-02-08 23:15
Hi @phillipcornwell, thanks for the screenshots and the logs, they are helpful! 

I tried reproducing with the same data you have and I now get the following:
![image](https://user-images.githubusercontent.com/572862/107293098-3ed03280-6a28-11eb-9f9e-240cdbe3a14b.png)

I am wondering if this was a problem with our tax provider (TaxJar) before? The API response we get back seems to be correct. It seems to rely only on zip code now.

I went to their [API demo](https://developers.taxjar.com/demo/) to do a quick check, it looks like the rate is also calculated as 7.55%
![image](https://user-images.githubusercontent.com/572862/107293276-9078bd00-6a28-11eb-81ec-882502e45593.png)

**Comment by harriswong** [comment] 2021-02-08 23:17
Tax is calculated by a third party vendor, we don't have control over the rates' correctness. We store the tax rate API responses in our "standard rate" table. Since the rate seems to be correct now, I am closing this issue. Please feel free to re-open it if it is still an issue.

**Closed by harriswong** 2021-02-08 23:17 UTC
Labels: Taxes, [Pri] High, [Type] Bug
