### ISSUE TITLE
Product tax classes won't work if there are spaces

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/woocommerce-services#2032] opened 2020-05-22 13:07 UTC
When product tax classes are set up using the [TJ established format](https://developers.taxjar.com/api/guides/#product-exemptions), the code isn't properly passed to the API, causing product exemptions to not reflect properly. They do work properly without spaces. So, for example, `Clothing–20010` works but `Clothing – 20010` doesn't.

To be consistent with available documentation, WCS should strip spaces to check for the tax code.

This was noticed while working on #2024

**Comment by bborman22** [comment] 2020-08-08 22:10
After some testing and review, it doesn't appear that the issue is caused by spaces in the Tax Class name. I confirmed that the WooCommerce Services TaxJar Integration pulls from the WooCommerce product tax class (https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-taxjar-integration.php#L624) and also confirmed that this tax class is based on the tax class slugs, which is always run through the sanitize_title function (https://github.com/Automattic/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L916). 

I also ran some tests with tax classes with spaces and without spaces and always received the same tax rate to confirm what I found. The likely explanation for the removal of spaces fixing the issue is that the tax class rates are removed and then repopulated from TaxJar after the a name change.

Tax Class with spaces
<img width="1344" alt="Tax Class after Rename" src="https://user-images.githubusercontent.com/68524302/89720566-5824f300-d9a1-11ea-9c1e-1403db203261.png">

Tax Class after renaming with no spaces
<img width="1344" alt="Tax Class after Rename" src="https://user-images.githubusercontent.com/68524302/89720396-a507ca00-d99f-11ea-9435-1a5e98e18b3b.png">

Tax Class after renaming with no spaces, repopulated
<img width="1344" alt="Tax Class after Rename" src="https://user-images.githubusercontent.com/68524302/89720638-4b54cf00-d9a2-11ea-91fb-78fa9f41a5c7.png">

This issue is being marked closed as the spaces in the tax class name does not appear to be the issue and the original issue may be related to previous tax rates stored in the tax rate table being applied incorrectly and the renaming of the tax class clears these out, fixing the issue. That scenario may require its own issue, but would require more information to reproduce.

**Closed by bborman22** 2020-08-08 22:10 UTC
Labels: Taxes, [Pri] Low, [Type] Bug, [Type] Good First Change
