### ISSUE TITLE
Automated Taxes are adding a Standard Tax line and charging tax on Shipping

### ISSUE THREAD

**Issue by ldr2273** [Automattic/woocommerce-services#1619] opened 2019-05-07 19:32 UTC
When using the Automated Tax feature and running through checkout, a Standard Tax line is being added in the backend, and tax is being charged on shipping as well.

**Steps:** 

1. Testing on latest versions of WC, Services, Storefront theme, with Jetpack also active.
2. Make sure there are no items in your Standard Tax rates: 

![Standard Tax](https://cloudup.com/cwHRurT928W+)
Link: https://cloudup.com/cwHRurT928W

3. Activate Automated Taxes:

![Automated Taxes](https://cloudup.com/cOjgF2rMuCX+)
Link: https://cloudup.com/cOjgF2rMuCX

4. Go to your store and run through checkout. You'll see that tax is being charged on shipping: 

![Tax on Shipping](https://cloudup.com/cKAcMomRBqy+)
Link: https://cloudup.com/cKAcMomRBqy

5. Once order is placed, navigate back to the Standard Tax settings, and you'll see this new line has been added, and shipping is taxed automatically: 

![New line item](https://cloudup.com/c90o7V4f3X9+)
Link: https://cloudup.com/c90o7V4f3X9

With Automated Taxes, there should be an option to NOT charge on shipping, and I do not believe this Standard Tax line should be added like this.

**Comment by frosso** [comment] 2020-11-10 17:24
Hey @ldr2273 !

The "shipping" checkbox is checked automatically because TaxJar is saying that based on the "from" and "to" addresses, shipping charges should be taxed.
This is by design and can be demoed at the following address: https://developers.taxjar.com/demo/
I'm not sure what your "from" address was, but you can also double check at that demo page and see if a `freight_taxable: true` attribute is added.
The `freight_taxable` is what controls the behavior of the "Shipping" checkbox.
https://d.pr/i/4Pv4ci

I'm going to close this under the assumption that TaxJar instructed us to tax shipping based on the store's address and the destination's address.

Thank you!

**Closed by frosso** 2020-11-10 17:24 UTC
Labels: Taxes, [Pri] High, [Type] Bug
