### ISSUE TITLE
Can't view packages in Packaging Manager when Admin user has products in cart

### ISSUE THREAD

**Issue by soungrong** [Automattic/woocommerce-services#1340] opened 2018-03-19 05:21 UTC
Hi,

[WooCommerce 3.3.3, WooCommerce 1.12.1, Jetpack 5.9, Wordpress 4.9.4]

1. None of my custom packages were shown in the **Packaging Manager**, and I couldn't add new ones.
(Woocommerce > Settings > Shipping > Packages)

2. So I tried "Save changes" on this page, with/without modifying anything and it gave me a generic message "There is an error with one of the fields please try again...". Although any settings that I changed were saved anyway.
(Woocommerce > Settings > Shipping Zones > Woocommerce Services)

I then tried removing all products from my cart, and that fixed it.

I'm not sure if it makes sense to allow editing of packages in the **Packaging Manager** when the admin  user has products in cart, but showing a descriptive error message in the **Packaging Manager** page, and not showing one in Woocommerce Settings for this situation would have been helpful

**Comment by dechov** [comment] 2018-03-21 00:37
Hi soungrong,

I wasn't able to reproduce the behavior where the presence of items in the cart breaks the package and shipping method settings forms. Can you confirm whether adding items back into your cart causes the issues to return? And if so, would you mind checking your browser console for errors, and reporting any you see?

This plugin should be unaffected by whether or not the cart has items in it, so it's possible that another plugin that would operate on the cart is interfering with the WooCommerce Services views — does that sound plausible based on the plugins installed on your site?

**Comment by v18** [comment] 2018-05-03 14:48
Hi @soungrong - I'm going to close this issue since we weren't able to get the problem to appear on our site while testing it out. If adding packages is still not working for you, can you see if there are any errors in the browser console? Feel free to re-open this issue if you have more questions or information for us.

**Closed by v18** 2018-05-03 14:48 UTC
Labels: [Status] Needs Author Reply
