### ISSUE TITLE
Discrepancies Between Calculated Rates And Rates Displayed While Printing Labels

### ISSUE THREAD

**Issue by harishankerr** [Automattic/woocommerce-services#917] opened 2017-03-06 16:00 UTC
The shipping rates being calculated by the plugin at checkout are different from the shipping rates being displayed at the label printing screen. 

To replicate:
1. Add product to cart, calculate shipping rates, and purchase the product. Note the rates calculated at checkout. ($10.40 for Priority Mail)
![Rate Calculated At Checkout](http://cld.wthms.co/c0RD/3A8RJEF7+)
http://cld.wthms.co/c0RD/3A8RJEF7
2. Check and compare the rates calculated when trying to print the shipping label (for the same product). ($42.03 for Priority Mail)
![Rates When Printing Shipping Label](http://cld.wthms.co/NJ2v/1GUL8TQ1+)
http://cld.wthms.co/NJ2v/1GUL8TQ1

As you can see, there is a significant difference in both rates.

**Comment by jeffstieler** [comment] 2017-03-21 15:39
Thanks for the report @harishankerr!

Can you share the dimensions/weight of the product and the info from the "packages" area in the label UI?

**Comment by harishankerr** [comment] 2017-05-09 05:32
Sorry about the delay in replying, @jeffstieler! I somehow missed this.

I did more digging, and the issue seems to be due to the fact that the rates are being calculated using weights, rather than product dimensions. 

The dimensions of the `Woo Logo` product are as follows:

![Dimensions](http://cld.wthms.co/ZlLbH+)
http://cld.wthms.co/ZlLbH

The weight is: **5.4 lbs**, while the dimensions are **16 x 16 x 12 inches**. 

Here's a screenshot of the label printing screen:

![Label Printing Screen](http://cld.wthms.co/dlzjf+)
http://cld.wthms.co/dlzjf

**Comment by harishankerr** [comment] 2017-05-10 08:00
Hey @jeffstieler ! I did more testing, and noticed similar issues with an entirely different product.

So, I created a new product, with the following dimensions: 
Weight: 10lbs.
Dimensions:  8x7x5 inches.

![Dimensions](http://cld.wthms.co/Ka750+0
http://cld.wthms.co/Ka750

USPS is configured with the Origin Address of Texas (the same as that of the shop location), with the zip code 78704.

![Zip Code](http://cld.wthms.co/uCIZ4+)
http://cld.wthms.co/uCIZ4

I added this product to cart, and tried shipping it to a California Address with the zip code `94107`, and the following rates were calculated:

![Texas Rates](http://cld.wthms.co/wuZeU+)
http://cld.wthms.co/wuZeU

As you can see here, the rates are as follows:
**Priority Mail:** $33.05
**Priority Mail Express:**: $87.80
**Media Mail Parcel**: $7.01
**Flat Rate Priority Mail:** $13.60

I chose the `Priority Mail` option, and concluded the order.

![Priority Mail Order](http://cld.wthms.co/4x8va+)
http://cld.wthms.co/4x8va

Here's a screenshot from the Label Printing Screen:

![Label Printing Screen](http://cld.wthms.co/myRZv+)
http://cld.wthms.co/myRZv

As you can see here:
**Priority Mail:** $9.09 (as opposed to **Priority Mail:** $33.05 from the rate calculation page)
**Express Mail:**: $33.35 (as opposed to **Priority Mail Express:**: $87.80 from the rate calculation page, but *same as the priority mail rates from the rate calculation page*)
**Media Mail Parcel**: $7.01 (this is the same as that from the rate calculation page)
**Parcel Select Mail:** $9.09 (was not available in the rate calculation page, but is the same rate as the Priority Mail page). 

Evidently, there's a discrepancy here. Could you please take a closer look? Thanks!

**Comment by jeffstieler** [comment] 2017-05-10 20:35
@harishankerr 

I was able to reproduce what you're seeing, but the "Origin address" being used for your label quote (94107) is different from the "Origin ZIP Code" set for customer-facing shipping quotes (78704).

Expand the "Origin address" card in the label printing dialog, and put in an Austin address with the 78704 - then you'll be getting more accurate rates.

*Note:* the rates you see for labels will likely be a few dollars cheaper than what you saw in the cart, because you're using retail rates in the shipping method - that's the only way I was able to see the `$33.05` rate. You should see `$30.21` for the corresponding label.

**Comment by harishankerr** [comment] 2017-05-15 06:07
Thanks for following-up, @jeffstieler. I'll do more digging locally, to try and investigate further. Will get back as soon as I have something. 👍

**Comment by jeffstieler** [comment] 2017-07-06 00:29
@harishankerr I'm doing some issue clean up - closing this since there hasn't been any movement.

Please reopen this issue if you notice it happening again!

**Closed by jeffstieler** 2017-07-06 00:29 UTC
Labels: [Pri] High, [Status] Needs Author Reply, [Type] Bug
