### ISSUE TITLE
County/Town tax not applied to Admin orders

### ISSUE THREAD

**Issue by FreshPhil** [Automattic/woocommerce-services#2039] opened 2020-06-05 17:01 UTC
3037379-zen

## Describe the problem
When manually making an order as the admin (`WooCommerce > Orders > Add New`), the `Recalculate` option does not factor in County/Town taxes and only returns the State tax.

This same issue does not happen on the customer interface.

## Steps to replicate
Set up your shop using a base address where a local county/town tax is applied, in addition to state tax.

Example: 22325 W 47th St, Shawnee, Kansas, US 66226

Add an item to your cart and proceed to checkout. Enter a local address in the zip code and observe the tax rate applied (9.6%). This is a combination of the state tax and county tax.

![](https://d.pr/i/WmjW7u+)
Image Link: https://d.pr/i/WmjW7u

Next, recreate the same order from the Admin dashboard (`WooCommerce > Orders > Add New`).
Recalculate the taxes and see that a tax called `KS Tax` has been applied at the rate of 7.9750%

![](https://d.pr/i/1ge5pZ+)
Image Link: https://d.pr/i/1ge5pZ

## Other info
When looking at the logs, you can see that the manually created order did not return city tax rate.

I noticed that the Admin generated request specifies:

`"to_street":false,"shipping"`

That seems to be the differentiator between the two requests.

## Customer Request
```
06-05-2020 @ 12:53:40 - :::: TaxJar Plugin requested :::: (WCS Tax)
06-05-2020 @ 12:53:40 - :::: TaxJar API called :::: (WCS Tax)
06-05-2020 @ 12:53:40 - Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"KS","from_zip":"66226","from_city":"Shawnee","from_street":"22325 W 47th St","to_country":"US","to_state":"KS","to_zip":"66226","to_city":"Shawnee","to_street":"22325 W 47th St","shipping":"0.00","plugin":"woo","line_items":[{"id":"3025-2bd235c31c97855b7ef2dc8b414779af","quantity":1,"product_tax_code":"","unit_price":"60","discount":"0"}]} (WCS Tax)
06-05-2020 @ 12:53:40 - Received: {"tax":{"amount_to_collect":5.76,"breakdown":{"city_tax_collectable":0.98,"city_tax_rate":0.01625,"city_taxable_amount":60.0,"combined_tax_rate":0.096,"county_tax_collectable":0.89,"county_tax_rate":0.01475,"county_taxable_amount":60.0,"line_items":[{"city_amount":0.98,"city_tax_rate":0.01625,"city_taxable_amount":60.0,"combined_tax_rate":0.096,"county_amount":0.89,"county_tax_rate":0.01475,"county_taxable_amount":60.0,"id":"3025-2bd235c31c97855b7ef2dc8b414779af","special_district_amount":0.0,"special_district_taxable_amount":0.0,"special_tax_rate":0.0,"state_amount":3.9,"state_sales_tax_rate":0.065,"state_taxable_amount":60.0,"tax_collectable":5.76,"taxable_amount":60.0}],"shipping":{"city_amount":0.0,"city_tax_rate":0.01625,"city_taxable_amount":0.0,"combined_tax_rate":0.096,"county_amount":0.0,"county_tax_rate":0.01475,"county_taxable_amount":0.0,"special_district_amount":0.0,"special_tax_rate":0.0,"special_taxable_amount":0.0,"state_amount":0.0,"state_sales_tax_rate":0.065,"state_taxable_amount":0.0,"tax_collectable":0.0,"taxable_amount":0.0},"special_district_tax_collectable":0.0,"special_district_taxable_amount":0.0,"special_tax_rate":0.0,"state_tax_collectable":3.9,"state_tax_rate":0.065,"state_taxable_amount":60.0,"tax_collectable":5.76,"taxable_amount":60.0},"freight_taxable":true,"has_nexus":true,"jurisdictions":{"city":"SHAWNEE","country":"US","county":"JOHNSON","state":"KS"},"order_total_amount":60.0,"rate":0.096,"shipping":0.0,"tax_source":"destination","taxable_amount":60.0}} (WCS Tax)
06-05-2020 @ 12:53:40 - :: Adding New Tax Rate :: (WCS Tax)
06-05-2020 @ 12:53:40 - {"tax_rate_country":"US","tax_rate_state":"KS","tax_rate_name":"KS Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":9.6,"tax_rate_class":""} (WCS Tax)
06-05-2020 @ 12:53:40 - Tax Rate ID Set for 24 (WCS Tax)
06-05-2020 @ 12:53:40 - :: Tax Rate Found :: (WCS Tax)
06-05-2020 @ 12:53:40 - {"24":{"rate":9.6,"label":"KS Tax","shipping":"yes","compound":"no"}} (WCS Tax)
06-05-2020 @ 12:53:40 - :: Updating Tax Rate To :: (WCS Tax)
06-05-2020 @ 12:53:40 - {"tax_rate_country":"US","tax_rate_state":"KS","tax_rate_name":"KS Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":9.6,"tax_rate_class":""} (WCS Tax)
06-05-2020 @ 12:53:40 - Tax Rate ID Set for 24 (WCS Tax)
```

## Admin Request
```
06-05-2020 @ 12:55:43 - :::: TaxJar Plugin requested :::: (WCS Tax)
06-05-2020 @ 12:55:43 - :::: TaxJar API called :::: (WCS Tax)
06-05-2020 @ 12:55:43 - Requesting: taxjar/v2/taxes - {"from_country":"US","from_state":"KS","from_zip":"66226","from_city":"Shawnee","from_street":"22325 W 47th St","to_country":"US","to_state":"KS","to_zip":"66226","to_city":"SHAWNEE","to_street":false,"shipping":"","plugin":"woo","line_items":[{"id":"3025-1070","quantity":1,"product_tax_code":"","unit_price":"60","discount":"0"}]} (WCS Tax)
06-05-2020 @ 12:55:44 - Received: {"tax":{"amount_to_collect":4.79,"breakdown":{"city_tax_collectable":0.0,"city_tax_rate":0.0,"city_taxable_amount":0.0,"combined_tax_rate":0.07975,"county_tax_collectable":0.89,"county_tax_rate":0.01475,"county_taxable_amount":60.0,"line_items":[{"city_amount":0.0,"city_tax_rate":0.0,"city_taxable_amount":0.0,"combined_tax_rate":0.07975,"county_amount":0.89,"county_tax_rate":0.01475,"county_taxable_amount":60.0,"id":"3025-1070","special_district_amount":0.0,"special_district_taxable_amount":0.0,"special_tax_rate":0.0,"state_amount":3.9,"state_sales_tax_rate":0.065,"state_taxable_amount":60.0,"tax_collectable":4.79,"taxable_amount":60.0}],"shipping":{"city_amount":0.0,"city_tax_rate":0.0,"city_taxable_amount":0.0,"combined_tax_rate":0.07975,"county_amount":0.0,"county_tax_rate":0.01475,"county_taxable_amount":0.0,"special_district_amount":0.0,"special_tax_rate":0.0,"special_taxable_amount":0.0,"state_amount":0.0,"state_sales_tax_rate":0.065,"state_taxable_amount":0.0,"tax_collectable":0.0,"taxable_amount":0.0},"special_district_tax_collectable":0.0,"special_district_taxable_amount":0.0,"special_tax_rate":0.0,"state_tax_collectable":3.9,"state_tax_rate":0.065,"state_taxable_amount":60.0,"tax_collectable":4.79,"taxable_amount":60.0},"freight_taxable":true,"has_nexus":true,"jurisdictions":{"city":"SHAWNEE","country":"US","county":"JOHNSON","state":"KS"},"order_total_amount":60.0,"rate":0.07975,"shipping":0.0,"tax_source":"destination","taxable_amount":60.0}} (WCS Tax)
06-05-2020 @ 12:55:44 - :: Tax Rate Found :: (WCS Tax)
06-05-2020 @ 12:55:44 - {"24":{"rate":9.6,"label":"KS Tax","shipping":"yes","compound":"no"}} (WCS Tax)
06-05-2020 @ 12:55:44 - :: Updating Tax Rate To :: (WCS Tax)
06-05-2020 @ 12:55:44 - {"tax_rate_country":"US","tax_rate_state":"KS","tax_rate_name":"KS Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.9750000000000005,"tax_rate_class":""} (WCS Tax)
06-05-2020 @ 12:55:44 - Tax Rate ID Set for 24 (WCS Tax)
06-05-2020 @ 12:55:44 - :: Tax Rate Found :: (WCS Tax)
06-05-2020 @ 12:55:44 - {"24":{"rate":7.975,"label":"KS Tax","shipping":"yes","compound":"no"}} (WCS Tax)
06-05-2020 @ 12:55:44 - :: Updating Tax Rate To :: (WCS Tax)
06-05-2020 @ 12:55:44 - {"tax_rate_country":"US","tax_rate_state":"KS","tax_rate_name":"KS Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":7.9750000000000005,"tax_rate_class":""} (WCS Tax)
06-05-2020 @ 12:55:44 - Tax Rate ID Set for 24 (WCS Tax)
```

**Comment by FreshPhil** [comment] 2020-06-05 17:02
Set to critical given the fact that this has financial and legal implications for users charging/collecting the wrong tax amount.

**Comment by c-shultz** [comment] 2020-06-12 22:07
Reopening because the fix caused #2044. We'll revisit making recalculation work for existing orders. #2018 is not reverted which added correct tax calculation on new orders. 

#2041 is reverted which removes street-level tax calculation on existing orders. This functionality has always been missing from existing orders, so this was the safest change to make near the end of the week.

**Comment by c-shultz** [comment] 2020-06-12 22:07
Downgrading to high because:

>This functionality has always been missing from existing orders

**Comment by johndcoy** [comment] 2021-04-12 16:02
Another request for this 3704043-zen

**Comment by harriswong** [comment] 2021-05-26 22:41
> The expectation to ensure tax reports reflect the specific location would be to also include the postal code/County/Town in the Tax Name when the tax table is created after a successful order.

@johndcoy I think this is resolved by this other issue [here](https://github.com/Automattic/woocommerce-services/issues/2226).

**Comment by harriswong** [comment] 2021-05-26 22:48
I can't reproduce this anymore. I followed the description and when I create an order via checkout, I do see 9,.6% tax as follow:
![image](https://user-images.githubusercontent.com/572862/119740873-e0e22200-be41-11eb-8241-5a71708d1025.png)

Inside admin, manually creating an order with the same address, I get 9.6% as well:
![image](https://user-images.githubusercontent.com/572862/119740900-f0fa0180-be41-11eb-9b72-3981d6c52efb.png)

Double checking against TaxJar's rate, also 9.6%:
![image](https://user-images.githubusercontent.com/572862/119740955-0707c200-be42-11eb-969b-290cb74b246d.png)

I am closing this. Please feel free to re-open the issue if it is still an issue.

**Closed by harriswong** 2021-05-26 22:48 UTC
Labels: Taxes, [Pri] High, [Type] Bug
