### ISSUE TITLE
Move and rename 'Other Services'

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#964] opened 2017-03-29 14:36 UTC
In user tests, we noticed that users checked the 'Other Services' box without double-checking that the services contained there were right for them.

This should be fixed using these two ways:
1. Move the option to the bottom
2. Rename it to indicate that it's 'dangerous' or needs to be double-checked. Some ideas are 'Advanced Services', 'Speciality Services' etc

Some other ways to help:
- add a description for the services
- visually differentiate it

#user-test-march-2017

**Comment by jeffstieler** [comment] 2017-03-30 14:46
Duplicate of https://github.com/Automattic/woocommerce-services/issues/948 - closing.

**Closed by jeffstieler** 2017-03-30 14:46 UTC
Labels: UI / UX, [Type] Enhancement
