### ISSUE TITLE
Let non-master Jetpack admins accept TOS

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1393] opened 2018-05-09 17:38 UTC
We should let non-master Jetpack admin users accept the TOS on behalf of the site. We may need to make sure each _new_ admin user accepts the TOS (need to verify this).

Ref: p7bbVw-2w7-p2

**Comment by laurendavissmith** [comment] 2019-10-01 14:48
Closing as dupe of #1653

**Closed by laurendavissmith** 2019-10-01 14:48 UTC
Labels: On-boarding, [Type] Bug
