### ISSUE TITLE
 Option to select not working

### ISSUE THREAD

**Issue by Eugene-pro-19** [Automattic/woocommerce-services#2183] opened 2020-09-16 08:07 UTC
when using woocommerce services plugin option to **select** all products or plugins or else don't work.I deactivated all plugins finally woocommerce services plugin bug came up.theme child theme storefront theme.

**Comment by frosso** [comment] 2020-09-16 14:03
Hey @Eugene-pro-19 ,

Thanks for tracking. This seems a duplicate of https://github.com/Automattic/woocommerce-services/issues/2165 , can you please confirm?
If so, the issue will be fixed by the next release patch: https://github.com/Automattic/woocommerce-services/pull/2181

Thanks again!

**Comment by c-shultz** [comment] 2021-06-30 18:38
This appears to be fixed now by #2181

**Closed by c-shultz** 2021-06-30 18:38 UTC
