### ISSUE TITLE
No Tracking for First Class Shipment

### ISSUE THREAD

**Issue by peterfabian** [Automattic/woocommerce-services#2021] opened 2020-05-04 16:31 UTC
When using woocommerce services to create shipping labels, on wordpress, it states that tracking information is included for USPS - First Class Mail. However, once the label is purchased and made, there is no tracking number.

**To Reproduce**

1. Go to"WooCommerce" > Orders > Select Order for Shipment
2. Click on 'Create Shipping Label'
3. Continue to 'Shipping Rates' and Select 'USPS - First Class Mail (includes USPS tracking)
4. Purchase Label
5. See Issue - No Tracking Number is on the label, or available in the Woocommerce 'Shipment Tracking' on Right Hand Side of Order Page.

![80873611-8945a700-8c7f-11ea-9a17-e499954a87f7](https://user-images.githubusercontent.com/2207451/80989458-3e6d9000-8e35-11ea-8450-aa4cf77a1e3b.png)

**Expected behavior**
I expect for their to be a tracking number provided on the label and in the Shipment Tracking section.

Since I can't transfer across orgs, issue migrated manually from https://github.com/woocommerce/woocommerce/issues/26363
cc @AllegiantGaming

**Comment by AllegiantGaming** [comment] 2020-05-04 18:53
@peterfabian why is this closed? The issue is not resolved.

**Comment by c-shultz** [comment] 2020-05-04 19:08
Hey @AllegiantGaming ,

This issues is still open. The original issue was closed because the shipping features are a part of the WooCommerce Services plugin. 

Can you tell me more about what version of WooCommerce Services you are running? There was originally a problem with how shipping features (like tracking) were displayed for First Class Mail. First Class Mail should not have display that tracking is available. This was fixed in the 1.23 release of WooCommerce Services. You should be able to just update the plugin to the latest version to resolve this display issue.

Let us know! Thanks.

**Comment by AllegiantGaming** [comment] 2020-05-04 19:38
Hi Chris,

Thanks for your reply. I have updated the plug-in, and see that tracking is no longer mentioned for First Class.
Can you please explain why this was removed? I would like to ship via First Class with tracking.


Sincerely,


Brittany Godin, Co-Founder
Allegiant Gaming, LLC


brittany@allegiantgamingco.com<mailto:Noah@allegiantgamingco.com> | www.AllegiantGamingCo.com<http://www.allegiantgamingco.com/> | (832) 437-0195







________________________________

**Comment by c-shultz** [comment] 2020-05-04 20:08
Brittany,

Thanks so much for confirming! 

There was a display issue in WooCommerce Services that showed tracking as an option even though USPS didn't provide it.

USPS doesn't provide tracking as a feature for First Class Mail, so we don't have the ability to enable that for you. For packages, USPS offers tracking for First Class service, but they don't offer it for First Class envelopes. [You can read more about that differences here](https://faq.usps.com/s/article/What-are-the-Types-of-First-Class-Mail#what_are) from USPS.

We hope the improved feature display in our latest release helps show all the different features of each service option when you're comparing rates.

I'm going to go ahead and close this issue since it was resolved in the 1.23 release. Thanks for contacting us!

**Closed by c-shultz** 2020-05-04 20:08 UTC
