### ISSUE TITLE
USPS SCAN forms for shipping labels

### ISSUE THREAD

**Issue by asuh** [Automattic/woocommerce-services#1650] opened 2019-08-09 19:13 UTC
For bulk shipping of packages, USPS provides a service called Shipment Confirmation Acceptance Notice (SCAN), which allows people to print out a bar code to scan that will represent many packages with created USPS postage labels

WooCommerce Services plugin makes creating and buying USPS labels convenient, but it would be more convenient for those who have hundreds of orders a day to take these created labels and tracking numbers to reduce the time the post office takes to scan all the packages into the system.

You can find the API here:
https://www.usps.com/business/web-tools-apis/scan-api.htm

**Comment by jconroy** [comment] 2019-10-04 16:01
Closing in favor of tracking popularity of the this feature on the [Woo ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/37802947-usps-shipment-confirmation-acceptance-notice-scan)

**Closed by jconroy** 2019-10-04 16:01 UTC
Labels: Move to Ideas Board

**Comment by asuh** [comment] 2019-10-04 16:09
Disappointing, but I had to at least try.

**Comment by chvillanuevap** [comment] 2020-08-01 19:15
How does the popularity tracking work? Is there a threshold before the Woo team decides to implement something?

**Comment by asuh** [comment] 2021-01-11 02:53
I want to document this here from additional conversations and research, for others to reference if they find this thread.

[In the SCAN API documentation](https://www.usps.com/business/web-tools-apis/scan-api.htm#_Toc44319308), it says that the individual labels that are printed need to be marked as holding for manifest - HoldForManifest=”Y”.

Using the WooCommerce shipping plugin for shipping labels, the plugin doesn't make direct requests to USPS in order to create the label.

WooCommerce Shipping & Tax plugin is using a WooCommerce API service which lives at https://api.woocommerce.com/.  Since they're using their own service, it's not clear how label requests to USPS are being made.  Trying to create the SCAN form without having labels that are properly set up for them isn't going to work.

To put it simply, during the initial request to the Web Tools label APIs to generate the original shipping labels, which happens behind api.woocommerce.com, the labels must be requested with `HoldForManifest=”Y”` in order for them to be used with a later request to the SCAN API to generate a form for all labels with `HoldForManifest="Y"`.

Since it doesn't appear possible for us to know what's going on in the WooCommerce API or add/modify it in any way, someone at WooCommerce needs to add an additional feature to let users choose to hold shipments for manifest.  Users have to opt into that choice because most shipping labels won't need or require it.  They will then add the appropriate attribute into the code on their servers when communicating with USPS.

I would love for someone at Automattic working on this plugin to correct me that I'm missing something or wrong here.

**Comment by c-shultz** [comment] 2021-01-18 17:11
@asuh, 

I can confirm that the WooCommerce API would need to be enhanced to add support for this feature, so the changes would not be limited to the public repo.

**Comment by chvillanuevap** [comment] 2021-01-18 22:22
It would be great if you guys could look more into enhancing the API. The USPS is swamped right now. I have personally been asked by several USPS employees to provide them with a SCAN form to speed things up for them. It saves them a lot of time to just scan a single form vs 10, 50, or 100 packages.

**Comment by asuh** [comment] 2021-01-18 22:28
@chvillanuevap 's experience mirrors ours, where USPS has threatened multiple times to not take large quantities of packages because of the time it takes to scan each package. This highlights a real need of small businesses who could be shut out on days with lots of orders.

**Comment by chvillanuevap** [comment] 2021-01-18 23:19
@asuh For sure! I have to drive an extra 20 minutes every day to drop my packages at a USPS post office that has a Bulk Mailing Acceptance department because my local post office two blocks away won't accept my packages anymore without a SCAN form. And last week, even this bulk mailing department asked me for a SCAN form because they are just that swamped. 

USPS is so busy right now that they are not even scanning packages that have no SCAN form anymore when they first receive them. This has caused a lot of confusion with my customers because the packages will be in "Pre-shipment" for days or weeks, and then suddenly appear at their front door.

**Comment by asuh** [comment] 2021-03-13 00:50
I'm updating so admins can see that on the Ideas board for this plugin, the 2nd and 3rd most voted ideas are both for this idea and bulk printing in general.
~~https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=167367~~
~~https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/37802947-usps-shipment-confirmation-acceptance-notice-scan~~

I don't know what threshold is needed for Automattic to consider this idea. I truly hope highlighting this can bring it to the attention of developers asap. So many of us really need this functionality :)

(UPDATE 06-10-2023: Woocommerce Ideas forum appears to be deprecated, new URL is below)

https://woocommerce.com/feature-request/usps-shipment-confirmation-acceptance-notice-scan-for-shipping-labels/#

**Comment by asuh** [comment] 2026-05-10 14:31
Thankfully, here in 2026, this is implemented in WooCommerce Shipping plugin.

https://woocommerce.com/document/woocommerce-shipping/#USPS%C2%AE-scan-forms
