### ISSUE TITLE
Live rates do not work for armed forces addresses

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-services#2206] opened 2020-09-30 17:57 UTC
**Tickets:**
3362938-zen

Customer reporting that armed forces rates are not working for WooCommerce Services USPS live rates. 

In searching, it looks like these were purposely disabled:

https://github.com/Automattic/woocommerce-services/issues/979
916-gh-woocommerce-connect-server

The problem is that for those that still have legacy live rates, it does not report anything back. There is nothing added to the logs, and when debug is on, nothing is added to the notices. If these should be disabled and this is not a bug, can we have a message returned to the log and debugging that rates are disabled for armed forces addresses? 

Replicate by:
1. Enabling live rates for your site
1. Make sure shipping zone has armed forces regions set: https://d.pr/i/pktXyZ
1. Add product to cart and go to checkout
1. Enter address specified below
1. No logging or debugging info given

PSC 2 Box 14697
APO, AE 09012-0147
United States

**Comment by aleftick** [comment] 2020-10-01 18:17
If this is not a bug, we should also note the limitation in [our Docs](https://docs.woocommerce.com/document/woocommerce-services/).

**Comment by c-shultz** [comment] 2020-10-01 19:17
Thanks for the report and for digging up #979. We'll check into this and see if we can re-enable it since we do support customs forms now.

**Comment by tommyshellberg** [comment] 2020-10-15 13:01
It looks like there are two parts to this:

1) Live rates not working which is due to them being disabled on the connect server itself
2) Labels are disabled for military addresses. From what I can tell, this is done within the WS&T plugin itself.  

While investigating I was able to get live rates working by enabling them on the WCS however I couldn't select the military services which were enabled:

![Screen Shot 2020-10-15 at 2 45 28 PM](https://user-images.githubusercontent.com/6723003/96129581-15c6e780-0ef7-11eb-9697-7b62bae9ea7c.png)

![Screen Shot 2020-10-15 at 2 48 21 PM](https://user-images.githubusercontent.com/6723003/96129631-29724e00-0ef7-11eb-805b-151c81224f94.png)

I think it makes sense to rename this issue to handle being able to print labels and handle live rates in this issue:

1566-gh-woocommerce-connect-server

**Comment by tommyshellberg** [comment] 2020-10-20 08:31
Closing as this is taken care of entirely on the server-side through the following issue:

1566-gh-woocommerce-connect-server

**Closed by tommyshellberg** 2020-10-20 08:31 UTC
Labels: [Pri] High, [Type] Bug, [Type] Good First Change
