### ISSUE TITLE
Incompatibility with Checkout Block. Occasionally throw error ("ZIP Code does not match the selected state.")

### ISSUE THREAD

**Issue by iyut** [Automattic/woocommerce-services#2683] opened 2023-09-19 05:14 UTC
When using the checkout block or a block based theme like Blockbase or Tsubaki while [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) (WCS&T) is active, using a valid combination of state + ZIP will occasionally produce the following error for customers:

```
ZIP Code does not match the selected state.
```

### Steps to reproduce : 

1. Enable WooCommerce.
2. Install/activate/configure [Jetpack](https://woocommerce.com/products/jetpack/?aff=10486&cid=1131038).
3.Install/activate/configure [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) to provide automated taxation.
4. Modify the theme template so that it uses the Checkout Block instead of the checkout shortcode.
5. Try to make a purchase using the Checkout Block with any payment method (e.g. [Check Payments](https://woocommerce.com/document/cheque/))
6. Encounter the error.

Note for step 6: this may require using a guest checkout, clearing the browser cache, and/or attempting multiple different postcode/state combinations, as it's finicky if a postcode is used that's been validated before. Here are some that I use that can help with debugging:

Sacramento, California, US 95816
Beverly Hills, California, US 90210
Vinita, Oklahoma, US 74301
New York, New York, US 10001
Oxford, Mississippi, US 38655
Como, Mississippi, US 38619
Horn Lake, Mississippi, US 38637

This issue is related to this [WC Blocks issue #10847](https://github.com/woocommerce/woocommerce-blocks/issues/10847)

**Comment by ralucaStan** [comment] 2023-09-26 15:13
Another user report 7086560-zd-a8c

**Comment by Stella3** [comment] 2023-10-02 16:11
Any word on a fix for this? 

Is there at least a plugin I can temporarily roll back so we're not losing sales?

**Comment by ralucaStan** [comment] 2023-10-03 10:30
Hey @Stella3, I saw you already asked the same thing on the ticket https://github.com/Automattic/woocommerce-services/issues/2683 that will solve this issue, as it's not coming from the Checkout Blocks. 
I think it's safe to close this ticket as there is nothing actionable on our side.

I can recommend using the classic checkout, the shortcode version until this is fixed.

**Comment by Stella3** [comment] 2023-10-03 13:41
> Hey @Stella3, I saw you already asked the same thing on the ticket #2683...

? This is 2683. 

So, to be clear, there is no version of any plugin that can be rolled back? The old checkout is a poor user experience.

**Comment by ralucaStan** [comment] 2023-10-03 15:35
> ? This is 2683.

Thank you for catching this, I though I was looking at a ticket in the WooCommerce Blocks repository, where the issue was also reported.

> So, to be clear, there is no version of any plugin that can be rolled back?

There isn't any recommendation I can make with confidence about rolling back a plugin for now.

**Comment by Stella3** [comment] 2023-10-03 15:47
> Thank you for catching this, I though I was looking at a ticket in the WooCommerce Blocks repository, where the issue was also reported.

Thank you.

**Comment by devvnawaz** [comment] 2023-10-05 16:01
7127464-zen

**Closed as completed** 2023-10-06 03:03 UTC

**Comment by george-vice** [comment] 2025-05-26 04:07
I was experiencing this issue on my own site, and recorded the issue. 

I believe the issue is in the logic when we revalidate the shopper's address, that validation isn't returning the proper result. 
- In the video. I entered a wrong zip code 00000
- I then update the zip code to a proper zipcode associated with New York, 10011, but the error code still persists.  I can confirm that the right address was sent in for validation. 
- The odd thing is, when I refresh the page, the error code disappears and the new address is also saved.  
- But when I go to make the transaction the same error pops up and blocks the transaction from happpening

https://github.com/user-attachments/assets/94a6ced5-7e80-4f23-a0c2-289cfeca3415

**Comment by plaurent** [comment] 2025-05-28 18:39
@george-vice Any insights on this zip-state bug?  I too am running into this error when I use Autofill in Chrome on the checkout form, even though my state and zip code are correct.

**Comment by george-vice** [comment] 2025-05-30 05:15
> @george-vice Any insights on this zip-state bug? I too am running into this error when I use Autofill in Chrome on the checkout form, even though my state and zip code are correct.

My hunch is it's got to be related to some type of caching.  I noticed that when I enter in the correct state / zip, then I refresh the page, then the error goes away.
