### ISSUE TITLE
Tax for 2-worded county not calculated in manual order in v.1.22.5

### ISSUE THREAD

**Issue by thuautp** [Automattic/woocommerce-services#1963] opened 2020-03-19 08:58 UTC
2793721-zen

Customer has WC 4.0 and using WC Services for automated taxes. They've also set up some standard tax rates.

Tax rates for GB area now has been fixed in WC Services v.1.22.5, however, customer says tax still doesn't calculate for 2-worded county when added through a manual order. I can also replicate this on my site using their tax settings. Below are the steps to replicate:

1. Standard rates setup as below:
<img width="1323" alt="Screen Shot 2020-03-18 at 11 36 22 PM" src="https://user-images.githubusercontent.com/13119409/77048930-c91b3c80-69f9-11ea-85e9-277f6e4cbd94.png">

2. Created a manual order with an address in **Lancashire** county, tax rate for **Lancashire** shows up fine:
<img width="1076" alt="Screen Shot 2020-03-18 at 11 37 04 PM" src="https://user-images.githubusercontent.com/13119409/77049078-05e73380-69fa-11ea-9c8f-b9da189686f7.png">

3. Tested with an address in **West Yorkshire** county, tax rate doesn't show up for this county:
<img width="1087" alt="Screen Shot 2020-03-18 at 11 36 28 PM" src="https://user-images.githubusercontent.com/13119409/77048989-e4864780-69f9-11ea-8d72-d23034f35420.png">

Customer confirms that the fix in 1.22.5 fixed the issue for orders placed by their customers in the front-end, but not for orders placed manually.

**Comment by frosso** [comment] 2021-04-14 17:51
Hey @thuautp , thanks for the report!

I took a look and I wasn't able to reproduce the exact scenario. It looks like some of the taxes might have changed.
Now TaxJar is returning the same tax rate regardless of the state/county. So this is what the rates table looks like now: 
![Screen Shot 2021-04-14 at 12 36 13 PM](https://user-images.githubusercontent.com/273592/114754280-0564bd80-9d1e-11eb-88a0-4532145761eb.png)


I created 2 manual orders (as well as through the frontend) like in the scenarios you described, and in all cases I can see the tax rate being added to the orders:

Lancashire
![Screen Shot 2021-04-14 at 12 38 49 PM](https://user-images.githubusercontent.com/273592/114754613-6391a080-9d1e-11eb-977f-2ebfb9efcfec.png)


West Yorkshire
![Screen Shot 2021-04-14 at 12 38 22 PM](https://user-images.githubusercontent.com/273592/114754561-52e12a80-9d1e-11eb-9834-121235198b90.png)

I also tried setting up my tax rates like in the screenshot, and I am still seeing the tax calculated accurately (since the TaxJar API overwrites the values in the tax rates table)
![Screen Shot 2021-04-14 at 12 49 48 PM](https://user-images.githubusercontent.com/273592/114756021-eb2bdf00-9d1f-11eb-9e9e-b0b77f01be3c.png)
![Screen Shot 2021-04-14 at 12 50 14 PM](https://user-images.githubusercontent.com/273592/114756080-fb43be80-9d1f-11eb-83f2-e8c5b7159c5c.png)
![Screen Shot 2021-04-14 at 12 50 08 PM](https://user-images.githubusercontent.com/273592/114756081-fb43be80-9d1f-11eb-9080-70427243e414.png)


I'm going to close this for now, but feel free to reopen it in case there are new reports!

**Closed by frosso** 2021-04-14 17:51 UTC
Labels: Taxes, [Pri] High, [Type] Bug, [Type] Good First Change
