### ISSUE TITLE
First Class Package Service still not available.

### ISSUE THREAD

**Issue by briancwelch** [Automattic/woocommerce-services#1505] opened 2018-09-16 17:25 UTC
As per release notes today:

> Correctly purchase a "First Class Envelope" or a "First Class Package Service" label depending if the package is an envelope or not

My package is in a 20 x 20 x 6" box and I still only have First Class Mail as an option.  First Class Package Service disappeared about 2 weeks ago.  Please advise.

**Comment by DanReyLop** [comment] 2018-09-16 20:37
Hi Brian!

When you're purchasing a shipping label, you'll see `USPS - First Class Mail` whether you're using an envelope or a box. The difference is that if it's a box (like yours), the label will be slightly more expensive and it will have a tracking number. That's `First Class Package Service`, we're just not naming it that way because we think it's redundant (maybe we should).

For example, this is the rate I'm getting for a `8 oz` item in a box:
![screen shot 2018-09-16 at 21 27 02](https://user-images.githubusercontent.com/1715800/45600602-635e8680-b9f7-11e8-9859-6e35d2dbb169.png)

You can compare it with the USPS price list [here](https://pe.usps.com/text/dmm300/Notice123.htm#_c037), you'll see it corresponds with the `Package Service` (and so it will have tracking).

> First Class Package Service disappeared about 2 weeks ago.

I don't recall us changing the names of the services recently, I think it has always been just `USPS - First Class Mail` when you're about to purchase a label. Are you sure it said `First Class Package Service` before?

**Comment by briancwelch** [comment] 2018-09-17 06:17
> Are you sure it said First Class Package Service before?
I've been using this for about 2 years now and ship about 20 packages a day, and I am _almost_ 100% certain it did.  But I could be wrong.  The problem is that all labels returned now for first class are just ones for standard envelopes like mailing a letter, regardless of weight and dimensions of package.  Is there something else you may suggest on my end that could have caused this?

**Comment by briancwelch** [comment] 2018-09-17 14:06
<img width="590" alt="capture" src="https://user-images.githubusercontent.com/3002855/45628117-58d8d700-ba61-11e8-82c9-099b071ba976.PNG">
  These are the labels I now get.

**Comment by briancwelch** [comment] 2018-09-19 00:41
No problem, glad to help.  It says they selected First-Class Package Service and paid $4.50.

**Comment by DanReyLop** [comment] 2018-09-20 12:38
We haven't been able to reproduce this issue. Just to confirm, this is what's happening:
* You configured a `20" x 20" x 6"` box in `WooCommerce -> Settings -> Shipping -> WooCommerce Services` (or the item itself is `20" x 20" x 6"`)
* A customer bought something in your store, and selected `First-Class Package Service`
* You went to purchase a label for that order and (without modifying anything in the `Packages` step), you got a `USPS - First Class Mail` that's suspiciously cheap
* When you purchased that label, it was for an envelope and it didn't have any tracking number

If all that is true, I've done the same steps (and some variations of them) and couldn't reproduce it. If I've made some wrong assumptions in those steps, please tell me :)

The easiest way I can think of for us to reproduce this error is to have access to your site (or a `staging` copy of your site). I'm sure you're getting tired of this back-and-forth and I could keep asking you questions for days until I'm finally able to realize what's causing this.

Obviously, don't give us your password here :)

If you're willing to let us take a look, create a temporary administrator account for us on your WooCommerce site. For security purposes, use our email address `woologin@woocommerce.com`. Then send us the password using our [QuickForget](https://quickforget.com) service. You would paste the username and password into QuickForget, select `Save my secret`, and then send us the URL through [this contact form](https://www.woocommerce.com/my-account/create-a-ticket/). Please mention this GitHub issue so I can be alerted.

**Comment by briancwelch** [comment] 2018-09-21 17:02
Oh no problem man, I don't mind answering questions for days it just takes me a bit to respond.  Those steps are indeed correct.  I can provide an administrator account on the live site sometime early next week if that's OK.  Thanks for the help.  If there's anything else I can do, please feel free to let me know.

**Comment by jcarr71** [comment] 2019-03-25 22:29
I found this thread while searching on a similar problem, but I've been able to work through it with a caveat - PLEASE show the difference between First Class and First Class Package.  It's cumbersome to look at the total postage and assume, based on amount, that it will in fact be the label with tracking etc - especially having to purchase it before seeing the label.  THANKS!

**Comment by mouligreenlaw** [comment] 2020-06-25 23:31
This came up again in 3094140-zen

**Comment by mouligreenlaw** [comment] 2020-07-08 04:12
Another one here;
3125443-zen

**Comment by harriswong** [comment] 2020-10-26 23:23
Hi @mouligreenlaw, I am using this [USPS pricing sheet](https://pe.usps.com/text/dmm300/Notice123.htm#_c037) and this [USPS dimension sheet](https://pe.usps.com/text/dmm300/Notice123.htm#_c227) as a rough guide to determine what package is available for what shipping method (ie. "Priority", "First Class", etc). I have a few questions:

1. Are you using "custom package" or specific "service package"? What are the dimensions and weight please?

2. 
> When selecting the First Class as the shipping method, there is no indication whether it is First Class Letter or First Class package which is more expensive.

I want to double check if you are seeing 2 "USPS - First Class Mail" prices or just 1? If it is just one, then the price reflects on the packaging itself. For example, if the package is a 5x5x1 inch envelop with 1oz weight, it should return the pricing based on the "letters and flats" pricing. If we select a 10x10x10 inch box, with 10oz weight. It won't fit in any ["First class mail" criteria](https://pe.usps.com/text/dmm300/Notice123.htm#_c038) so it will fall into the ["First class package"](https://pe.usps.com/text/dmm300/Notice123.htm#_c038) category and return those rates. 

in WCS, "first class mail" or "first class package" have the following dimension and weight specifics:
First Class (Letter and Flats): 22"x18"x15" (55cm x 45cm x 38cm). 13oz (368g) max.
First Class Package Service: 22"x18"x15" (55cm x 45cm x 38cm). 15.99oz (453g) max.

If the package is outside of the above dimensions, no First Class rate is returned. 

### How I tested
1. Test against an envelop. 10x10x2 inches envelop, 2oz. This should fit under "Large envelop" specified [here](https://pe.usps.com/text/dmm300/Notice123.htm#_c227). 
![image](https://user-images.githubusercontent.com/572862/97238649-813e6e00-17af-11eb-808f-f3de1cc5e5e2.png)

2. Test against a package, 8x8x8 inches box, 10oz. This should fit under our requirement above. 
![image](https://user-images.githubusercontent.com/572862/97238782-cebadb00-17af-11eb-94fd-7ebfd54d6819.png)

I do see rates coming back. I hope these help! Please let me know if I missed something, otherwise we can close this.

**Comment by briancwelch** [comment] 2021-01-28 04:58
Pardon the latency of my own reply.  All seems fine on my end.

**Closed** 2021-01-28 21:39 UTC
Labels: Shipping Labels, [Pri] High, [Status] Needs Author Reply, [Type] Bug
