### ISSUE TITLE
Connect-a-thon: Bad order ID in URL results in 500

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#580] opened 2016-09-28 01:52 UTC
If you hack the order ID in the URL to a non existent order, you get this:

<img width="986" alt="screen shot 2016-09-27 at 6 52 07 pm" src="https://cloud.githubusercontent.com/assets/1595739/18897996/91af1c7a-84e3-11e6-8f60-ab3f4f0df90c.png">

This only seems to happen if connect is active

**Comment by jeffstieler** [comment] 2017-07-06 00:39
Closing - I can't reproduce this.

When mucking with the `?post=` ID, I get this error from WP: `You attempted to edit an item that doesn’t exist. Perhaps it was deleted?`.

The 500 you're getting looks a lot like Pressable's styling.

**Closed by jeffstieler** 2017-07-06 00:39 UTC
Labels: [Type] Bug
